### ISSUE TITLE
MPO/JPS 3D File Support

### ISSUE THREAD

**Issue by plberd** [owncloud/gallery#103]
Granted the whole OC doesn't care much about MPO (Multi Picture Object, usually generated by Fujifilm 3D cammeras and some other 3D cams/phones out there) files. But they are actually JPG files concatenated. Most linux programs can show these files because they are valid JPG files with something else at the end (another valid JPG file). In fact, the old OC Pictures app can show the left eye image with no problem (if I add the corresponding mime type).
But Gallery+ has some other constraint. When I try to open an MPO file it shows a scaled up generic image icon instead of the image. Even if it doesn't have a JPG extension there IS a valid JPG inside!
Is there any chance that MPO files could be supported in the future?

**Comment by oparoz** [comment]
Adding the mimetype only would be too much of a hack since we would have to add exceptions, but proper support via a provider shouldn't be too difficult.
The main problem is that we have to make modifications in `core` every time we want to add support for a new media type, so if this doesn't happen within the next 10 days, you're looking at full support in 4-6 months.

That's what adding support for a media type looks like:
https://github.com/owncloud/core/pull/14927

Anaglyph pictures could even be shown in the slideshow, but downloading both the stereo image and the left eye so that users can switch between them would most certainly slow down the

**Comment by oparoz** [comment]
OK, I've done some tests and this is a `core` issue. It needs to identify those formats as JPEGs, so please open a ticket there and I'll probably be able to fix this in 8.1.

Please add the ticket number here so that I can easily keep track of things.
