### ISSUE TITLE
Config file inheritance

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#107]
Master now has a way to configure albums using a simple text file (see #93).
Sorting inheritance is supported, meaning that you can set a sorting type and order for the top folder and all sub-folders will apply the same sort configuration.
It could also be possible to apply the same mechanisms to other variables, but I think it would make things more difficult to manage, unless we do things differently.
- Do you think it should be possible to inherit configuration properties?
- Would you rather control the behaviour of sub-folders using the top-folder configuration, by setting a flag allowing the setting to be applied to sub-folders? or
- Should sub-folders control their fate by each adding a flag letting the view know what to do?

**Comment by deMattin** [comment]
Most people will have default Foto folders and also some other folders which may have other sort of pictures in.
So as default Configuration in file root a global definition can be made - maybe only with copyright infos.
In foto folder root you can define other infos as in e.g. the picture folder root, where you collect scans or graphical pictures.
This descrptions should definitly be inherited!
Because in other case you have to give the same definitions (e.g. copyright) in any subfolder!

If you make descriptions like "Last vacations" or something like that, the inherit would also be ok, if you have a little bit of "clean sorting" in your file folder structure.
Who will make a subfolder in there with the fotos of last business trip?

Folder structure and naming is an inheritance by definition, I think!

So I see no really need to set an inherit flag. But it may make sense, if there will be a flag to NOT inherit the information in rare circumstances, where you don't want to pass on the parent folder configuration in subfolders.
But then this also should work on sorting!

Default inherit of complete configuration will also be more logical for user.
Sorting is inherited but description not? They are both in the same config file!

So my proposial would be to use the same inherit logic on sorting and description/info and perhaps define a new "not-inherit" flag to suppress the inherit feature to subfolders.

**Edit:**
Maybe the "not-inherit" flag could be divided into two features:
"`not-inherit-sorting`" and "`not-inherit-description`"
Not neccessary for me - but this way you have all possibilities.

**Comment by oparoz** [comment]
Thanks for detailing how it should work for you. We all like to organise our collections differently, so it needs to be flexible, while still being easy to use.

I need to make the feature available to more people, so that different configurations can be tested.

**Comment by deMattin** [comment]
I hadn't only described, how it should work single for me.
I tried to have a look at usual use case - also regarding some people messing with files and folder, that I know... ;)

Both solutions will work for all scenarios: inheritance or supress inheritance by default.
**But to make it simple and logical in use, there should be only _one_ logic for sorting and description.**
To pass on sorting and don't do this on description is confusing.

And not to pass on sorting options is also a feature somebody would like to have.
Example:
You have a main picture folder. In this folder you have a bunch of subfolders named by date prefix and short description (have seen this often and use it like that, too). This folder you would perhaps like to have sorted reverse to have newest on top. But if you call subfolders, they should be sorted "normal" named as default (without giving every folder its own config).
So not passing sorting can very likely be a good option in some cases.

Ok, I would like to see inheritance by default for sorting and description and flags in config to prevent this - optimal with two prevention flags, one for sorting and one for description (better to say: the remaining part of config).

Let's see, if someone has scenarios, where another approach would be better.

**Comment by oparoz** [comment]
You've described a case which works well for pictures, but inheritance by default would be a pain for a graphics designer per example

```
CLIENT A
D: client address, etc.
- Corporate ID
D (i): client address, etc.
-- Research
- Website
D: www.awesome.com
-- Navigation
-- Content pictures
D (i): www.awesome.com
- Ads
```

A lot of folders are unrelated and you would be forced to add a description, or worse, an empty one so that the top one doesn't show.

**Comment by oparoz** [comment]
For me that's an example which goes in favour of explicitly enabling inheritance. It's much less work if you don't want to add descriptions or sorting everywhere and have complex structures.

**Comment by deMattin** [comment]
Ok, I agree with your argumentation to deactivate inheritance by default.
Maybe it's also most user friendly - and also better to describe in a manual (in better english as mine ;)):
- you are able to create a configuration file in a folder to manipulate default sorting order and give information on content ....
- if you want to set this configuration also for the subfolders you have to set following flags ....

This seems to be straight forward.

And activation of inheritance with two configuration flags?
One for sorting and one for the remaining definitions in configuration file (comment, copyright, ...)?

**Comment by deMattin** [comment]
Is it possible to (always) rebase `sorting-buttons` branch to `master` if there are commits in master?
This way there's no need to switch back to master and you are able to work with sorting buttons not only for testing.

**Comment by oparoz** [comment]
Yes, you can rebase a branch based on another branch

**Comment by deMattin** [comment]
I didn't make myself clear. ;)
I should have written, if **you** could rebase the `sorting-buttons` branch on every change of `master` here on github.
Otherwise my locally rebased `sorting-buttons` branch will "forget" this rebase on any git pull of `sorting-buttons`, I think.

**Comment by oparoz** [comment]
I won't always. Maybe once a week, but I don't intend on doing too much work on the sorting-buttons branch. It needs a UI and can then be merged.

**Comment by deMattin** [comment]
Ok, thanks.
I like your approach with the implied 3D effect for the active button.
But maybe core designer team disagrees, because of ownclouds flat design and prefer a complete thicker border for active button or whatever.
I hope someone will have a look at it soon.

**Comment by oparoz** [comment]
Exactly. I did try to make the inactive button lighter, but it wasn't as effective.
The other problem is that those buttons are too graphical/complex looking compared to the rest. I've already wasted over 2 hours looking at various ways of doing things, so I'll let someone else do it from now on.
