### ISSUE TITLE
Review the PHP

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#11]
The rewritten Gallery app and soon to be called Media app needs some people to review its PHP code to make sure it's a sound base for the future.
The methods are kept short and the complexity low, in hope to make them easier to test.
#### 5 controllers
- HTML pages
- 2 Files controllers. One for calls from within OC and one for public pages

```
public function getFiles($location))
```
- 2 Preview controllers. Same configuration as above

```
public function getMediaTypes($slideshow = false)
public function getThumbnails($ids, $square, $scale)
public function getPreview($fileId, $width, $height, $download)
```
#### 2 middlewares
- Make sure sharing is enabled for public pages to work
- Make sure we have a valid token which is linked to a valid resource and that the user is authorised to access the page
#### 4 services
- FilesService looks for files to show

```
public function getMediaFiles($folder, $supportedMediaTypes)
```
- PreviewService generates and fixes previews

```
public function getSupportedMediaTypes($slideshow)
public function isPreviewRequired($file, $animatedPreview)
public function createPreview($file, $maxX = 0, $maxY = 0, $keepAspect = true, $base64Encode = false)
public function previewValidator($base64Encode)
```
- DownloadService prepares content to be downloaded

```
public function downloadFile($file, $base64Encode = false)
```
- ThumbnailsService provides information about what a thumbnail should look like, specswise

```
public function getThumbnailSpecs($square, $scale)
```
#### 1 environment class
- Holds everything that the services need in order to be able to access files
#### 1 http response type
- Returns images (previews or files as-is)
#### 2 other classes
- A smarter logger to make things easier before it's added to core
- A preview helper class

The code is documented, but there are some methods which are more complex than others:
https://github.com/interfasys/galleryplus/blob/master/service/previewservice.php
https://github.com/interfasys/galleryplus/blob/master/preview/preview.php
https://github.com/interfasys/galleryplus/blob/master/service/environmentservice.php

cc @MorrisJobke @Raydiation @LukasReschke @icewind1991 @georgehrke @libasys

**Comment by LukasReschke** [comment]
I will take care of this considering that it may be the official app in the future.

**Comment by oparoz** [comment]
Thanks!

**Comment by Raydiation** [comment]
Quick look, will review more tomorrow:

# EnvironmentService
* Authorization belongs into the controller usually.
* Icognito Mode no idea, it must be purged but I dont know how "required" it is

# Preview
* It feels kinda weird that a service uses a Template method but probably a core problem

# PreviewService
* A preview should not return a Response, that's the controller's job

Some general remarks:
* I like the formatting and coding practice, looks very clean :+1: 
* I get a feeling that you are sometimes mixing up controllers and services. The difference between the two is that a controller is tied to the protocol which is Http whereas a service is something like a library and is usage agnostic. This means that a service should never use anything that has something to do with Http constants, responses or requests.
* setting a lot of attributes when calling a method is usually a bad idea regarding services. A service is or should be more like a function and should not rely on state. That way the Api is clear and you can use a singleton. Consider the following examples:

```php
$service->calculateTemperature($unit);
$service->multiplyTemperatureBy(2);
$service->saveTemperature();
```

vs

```php
$temp = $service->calculateTemperature($unit);
$temp = $service->multiplyTemperatureBy($temp, 2);
$service->saveTemperature($temp);
```

The first example looks easier because it has less code but you have to know the exact order, meaning that its easier to create bugs and harder to figure out what is actually happening whereas the second example makes the order clear and you can rearrange it without having to read the source code

**Comment by BernhardPosselt** [comment]
Quick look, will review more tomorrow:

# EnvironmentService
- Authorization belongs into the controller usually.
- Icognito Mode no idea, it must be purged but I dont know how "required" it is

# Preview
- It feels kinda weird that a service uses a Template method but probably a core problem

# PreviewService
- A preview should not return a Response, that's the controller's job

Some general remarks:
- I like the formatting and coding practice, looks very clean :+1: 
- I get a feeling that you are sometimes mixing up controllers and services. The difference between the two is that a controller is tied to the protocol which is Http whereas a service is something like a library and is usage agnostic. This means that a service should never use anything that has something to do with Http constants, responses or requests.
- setting a lot of attributes when calling a method is usually a bad idea regarding services. A service is or should be more like a function and should not rely on state. That way the Api is clear and you can use a singleton. Consider the following examples:

``` php
$service->calculateTemperature($unit);
$service->multiplyTemperatureBy(2);
$service->saveTemperature();
```

vs

``` php
$temp = $service->calculateTemperature($unit);
$temp = $service->multiplyTemperatureBy($temp, 2);
$service->saveTemperature($temp);
```

The first example looks easier because it has less code but you have to know the exact order, meaning that its easier to create bugs and harder to figure out what is actually happening whereas the second example makes the order clear and you can rearrange it without having to read the source code

**Comment by oparoz** [comment]
Thanks for the first look and the pointers :). I'll see what I can do tomorrow. 
- [x] Regarding the Response, everything was in the controllers to begin with and after all the re-factoring, I forgot to step back and check that everything was in place. This makes me think that maybe a checklist for devs could have its place in the documentation. Do this, don't do that, etc.
- [x] Incognito mode is still required. There is a link in the doc to the discussion currently happening around it
- Regarding the template method, it's also available at the root level, simply `mimetype_icon($mime)`, but it's deprecated.
- Authorisation... I had it in the controller originally, but because `@PublicPage` is used in 2 different controllers, I thought it would be best to let the middleware set up everything through the EnvironmentService. I'm open to suggestions.
- [x] "_This means that a service should never use anything that has something to do with Http constants, responses or requests_"
  I'm guessing you're making reference to my use of Http:STATUS_XXX in EnvironmentService and you're right, I didn't think of making the service HTTP agnostic. I started off with exceptions and thought it was simply overcomplicating things

**Comment by oparoz** [comment]
OK @Raydiation, I've moved things around.
- HTTP responses have been moved back to the controllers
- The environment service has been split in two
- An environment Class has been created to hold the variables the services need to do their job
- The tokencheckmiddleware is now the envcheckmiddleware and makes sure the token and the resource is links to are valid before sending initialising an environment object
- Some exceptions have been created in order to bubble up problems
- Controllers make the decision whether a file should be converted or downloaded as is
- Introduced a download service

OP updated

**Comment by oparoz** [comment]
OP updated with some upcoming changes. Mainly, there is now a FilesController talking to a FilesService and a PreviewController talking to a PreviewService.

**Comment by oparoz** [comment]
Will use this to write specs. Individual issues can be opened if someone finds cause for concern in the current code.
