### ISSUE TITLE
Find a way to differentiate between local and inherited descriptions

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#114]
A visitor will stop clicking on the info button after having realised he's always getting the same inherited text. Doing so, he might miss local descriptions which could be of interest to him.

A spark overlay could indicate a change, but that could be misconstrued for new content.
Maybe we should darken a corner?

**Comment by deMattin** [comment]
Something like this?
![image](https://cloud.githubusercontent.com/assets/5565503/7040330/2f86df5a-ddce-11e4-9f03-e22d7c874ab6.png)

**Comment by oparoz** [comment]
Yes. Do you know of any implementation of something similar?
Should the marker be added when the description is local or if it's inherited?

**Comment by deMattin** [comment]
I think, a local description should be marked or highlighted and should be more prominent.
Sadly I have not seen this in an (web) app before, but I think, this can be realized with some css.

Another less prominent way to mark a local description could be, to simply dim (set another opaque level) the "i"  for an inherited info and display it like actual for a local info.
I think, this would be much more easily to implement and will provide the information, too.
If there's no info, the "i" button is hidden. So there you get the 3 different states:
- no button: no info
- "dimmed i" button: inherited information
- "normal i" button: local information

**Comment by oparoz** [comment]
Adding a marker shouldn't be a problem with CSS
The only problem with dimming is that a user landing on a page with an inherited description would not necessarily understand why the button is dimmed/looks broken.

**Comment by deMattin** [comment]
Hmm - i don't think, it looks broken, if it is dimmed.
The inactive sorting button behaves the same and dimming here stands for "inactive".
For "i" button dimming could stand for "not as important".
I would like it as a discrete way to provide the information of different information content.

But any way to mark the ineritated/local state of the information should be a unobtrusive mark - not to prominent. Because it is not a really important information to become an eye catcher on change.

Neither a dimming nor a marker is really intuitive to a user - he doesn't know, why this button changes its look and has to try and see, what happens.
But that's a thing of nearly all buttons. The file app button e.g. isn't intuitive, too. You use it and then you understand the meaning of the 3 lines with a dot at the front.

User only notices, that there is a difference; both ways ...

But I have learned the last weeks (here and in core), that UI is a thing, where 20 user have 30 concepts ... ;)

So I only can give my point of view and it's on you to decide. :)

**Comment by oparoz** [comment]
With the sorting button, you see both states at the same time, so you understand right away. The design cues would suggest that the button is inactive, which is not the case.

I'm probably going to introduce a fireworks animation marker. I've found one which is only 9MB. It's very colourful as well, so it should be easy not to miss ;)

And you're right, this project needs designers, because I can say what doesn't work, from training and experience and I have my own opinions, but creating new graphics and making sure it all fits together is a job for a professional.

**Comment by deMattin** [comment]
Designers are good to have.
But it's also good to have in mind, that a theming should be as easy as possible.
So it will suit all users.

As an example:
For me and my co-users of the ownCloud the linespacing of files app is much too big. And this is no matter of "design" but more a worse user experience, if you have such line spaces in desktop browsers. So regarding touch pad usability(?) is contrarary desktop use.
Theming this is in the file app (reduce line spacing) is a pain but possible.
Designers often think, that there opinions (based on whatever) are the only way to make it the right way and often they prefer a solution, that fits for the masses and all cases but then it doesn't fit at all for individuals or a special user group. And so it doesn't fit well on anybody because it's a compromize for all use cases.
That designers thoughts often don't hit the needs and sometimes are only "modern trends", you see on any discussion on GUI concepts like ribbons, modern UI of Windows 8, new Gnome, ...
But all in all it's good to have them, I think. It's a hard job, where there's always someone, who doesn't like, how they do it ... ;)

**Comment by oparoz** [comment]
I'm going to go with something like this
![Marked icon](https://oc8demo.interfacloud.com/index.php/s/MdD45I2ngXcJFLQ/download)

**Comment by deMattin** [comment]
This marker is not my favorite, but I like the slide in effect. ;)

Marking works, but there are some issues:
1. I always get `Uncaught TypeError: Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked.` error in `marked.min.js:6` in browser.
2. If I create a local (overwriting) definition, I don't get it. It's always "spinning wheel" in info box.
3. Only creating a definition in a subfolder also let's never ending spin the wheel.

Can not investigate it further for now ...

Edit:
Seems to be an issue, if you define a description file (readme) in config of subfolders..
Only overwriting album information and default sorting seems to work.

Edit 2:
And with deactivating inherit in overwriting "cnf" file, there also seems to be an issue - it is inherited and not ignored.
Have to test it further but not tonight any more ... ;)

**Comment by oparoz** [comment]
I can't reproduce, so please open a separate issue for each problem and give step by step instructions.
You might have some config files using the old format which interfere. they should be ignored, but I might have forgotten a check.

**Comment by oparoz** [comment]
In the meantime, I've now done this:
https://github.com/interfasys/galleryplus/commit/0ebd40f0d09183d17e4ab55afbe0882ef1cb8ba1

**Comment by oparoz** [comment]
I think your Yaml file is not properly configured. I got my new error message when a description was not properly spread over multiple lines.
