### ISSUE TITLE
Not all folders containing pictures visible in gallery

### ISSUE THREAD

**Issue by Pantek59** [owncloud/gallery#132]
The gallery app used to list all folder containing pictures. This was the case until the recent update to OC 7.0.1 or OC 7.0.2 (not sure, unfortunately). 

Now, however, only three of the four (external storage) folders are shown, when I start the gallery app. The missing folder is still shown correctly in the files app and it opens with all sub-folders and pictures without any problems in the gallery app when I enter the URL manually.
This behaviour has not changed in the version currently running, OC 7.0.3. 

I have unfortunately no idea what makes the missing folder special and suddenly causes it to be hidden. New folders in OC containing pictures are shown correctly.

There are no error messages to be found in the logs of owncloud or apache with regard to the gallery app.

**Comment by paonza** [comment]
I have the same problem... OC 7.0.4 and gallery 0.5.4

**Comment by paonza** [comment]
I think the problem is this: 

if the first folder doesn't contain al least 1 jpg none of the folder or the other subfolder are shows for this branch...

Example: 
my file structure:
photos[folder]
+2010[folder]
++2010_first_trip[folder]
+++img1.jpg
+++img2.jpg
++2010_second_trip[folder]
+++img3.jpg
+++img4.jpg
+2011[folder]
++2011_first_trip[folder]
+++jpg[folder]
++++img5.jpg
+++img5.NEF
++2011_second_trip[folder]
+++img6.jpg

EXPECTED GALLERY FOLDERS:

photos
+2010
++2010_first_trip
++2010_second_trip
+2011
++2011_first_trip
+++jpg
++2011_second_trip

BUT

i can only see "2010" folder and his sub-folders but NOT "2011" beacuse "2011_first_trip" does not contain any jpg in the root.... 

gallery tree have only:
photos
+2010
++2010_first_trip
++2010_second_trip
STOP!

if i force to load "apps/gallery#photos/2011", only "2011_second_trip" shows....

sorry for my bad english! :-)

ciao
Fabio

**Comment by oparoz** [comment]
@Pantek59 - It could be an issue with using external shares. In my tests on OC7, the gallery app will time out if there are more than a few pictures on an external folder as the transfer is horrendously slow, even between 2 OC instances on the same server.

@paonza - In my tests, using fresher code than 0.5.4, the gallery would fill the top album using pictures from the lower folders. If you want me to test this, please prepare a zip with the hierarchy that you've described. Test it on your setup and if it fails, I'll test on mine to see if I experience the same thing.

**Comment by Pantek59** [comment]
I'm only running one OC instance but I'm linking folders outside the OC-folder structure as external folders. It could still be a speed problem, though.

After the update to OC 7.0.4 the behavior changed slightly. Now all the files and folders are shown correctly the first time I navigate into the picture folder. As long as I keep going deeper into the folders, things are fine now. But if I try to go back up a folder level all picture beneath the first line if pictures are missing. It looks a bit as if the rest had been cut off. The problem disappears if I start the picture app again and start at top folder level again.

**Comment by oparoz** [comment]
Please re-open in Gallery if you're still having issues with external shares.
