### ISSUE TITLE
Is it possible to increase the image resolution of the slideshow for Gallery+?

### ISSUE THREAD

**Issue by ghost** [owncloud/gallery#135]
I use ownCloud to store photos I took, and I use web slideshow to browse them.

And I notice the image quality on Gallery+'s slideshow is not as sharp or not as clear as on the Pictures app(The one came with ownCloud)

I think the reason is because the Pictures load the image with its original resolution
![pictures slideshow resolution](https://cloud.githubusercontent.com/assets/12343360/7538037/cd2a50de-f5cf-11e4-82f8-1e8c3402d5b8.png)

And Gallery+ resize the image to a smaller size...
And when I zoom in, the detail are gone and the picture looks blur
![gallery resolution](https://cloud.githubusercontent.com/assets/12343360/7538039/d0b83432-f5cf-11e4-8cea-712461980762.png)

I think it would be nice if Gallery+ can use a larger resolution or the original resolution for the slideshow.

**Comment by oparoz** [comment]
Thank you for the feedback.

Without zooming, the pictures should look the same, because, as you can see in your screenshots, we're requesting a picture which fits exactly in the available space (1920x989). The reason for doing so is to be able to retrieve the image faster, as it's lighter. It also saves bandwidth on mobile.
The picture may look crisper in Pictures because the browser is shrinking it to make it fit or it could be blurrier in Gallery+ if the resizing routine is degrading the quality significantly or if the zooming library is smoothing the image.

I'm going to do a test to assess if I see a significant difference or not.

Now, when zooming, you will get a blurry picture, because we zoom in the picture which was loaded. I guess we could introduce a user setting which allows someone to load pictures at twice the window resolution.

**Comment by deMattin** [comment]
Could it be a solution to reload the picture with full resolution only if you zoom in?
For fast browsing in gallery it's perfect now, as it is.
Giving double resolution as custom setting won't be good in any case, because speed will be reduced if you don't use zooming and if you go in detail with zooming, the customized double resolution could possibly not be enough with a highres pic.

In cases you zoom in, it would be best to reload this picture in full resolution!

BTW: I don't like this zooming with scroll wheel at all because I use the smooth scrolling extension of my logitech mouse (giving great experience in text scrolling) and so this zooming is often initiated accidentially.
So (for me) it would be best to zoom in with clicking on the pic, using zoom buttons or something similar.
The scroll wheel is for scrolling and not for zooming!
But this is another issue ... ;)

**Comment by oparoz** [comment]
So, I've looked at the same picture loaded in the 2 apps side-by-side and the pic on Gallery+ is crispier, due to the filter used, but it's not that different.

So the first thing would be for @wcsun to confirm that he sees a problem there, when **not** zooming.

@deMattin - I think reloading the picture would kill the UX. Load slideshow, wait 5s, click for HD, wait 5s, zoom.
If the double resolution is a setting, then the user knows what he's getting into when enabling it, but as you've mentioned, it wouldn't be a 100% working solution.
What would work is to actually pre-process all large pictures to turn them into properly zoomable pictures like in this demo: http://monochrome.sutic.nu/2010/10/07/bigshot.image.1.html

Yes, please file an issue if you think scrolling-zooming doesn't work for you. It works for me :)

**Comment by deMattin** [comment]
A nice and simple solution could be to give the user a "reload this pic in full resolution" button.
What do you think?
This way, the user knows, he has to wait for a reloading in this special case and also no changes in old code are neccessary.
And a user who likes to zoom in better quality doesn't need to live with a slower gallery if not using zooming.

This bigshot/monochrome thing is great! Also and especially the use of gui elements is intuitive and nice!
But regarding my last experinces with gui discussions, I see no chance to get something (looking) like this in owncloud ... ;))

And with the scrolling/zooming I won't open an issue because I know, that many users like scrolling with the wheel and so I see no chance to get a change here.

**Comment by oparoz** [comment]
I think what people will want is to be able to zoom in with every picture, during a slideshow, when showing pictures taken during a trip per example, but an HD button could be handy.
Now that features can be enabled/disabled, it's not that much of a problem to add buttons or to simply enable an advanced interface for button lovers :)

**Comment by b1ggjoe** [comment]
FYI...

https://github.com/owncloud/galleryplus/issues/143

BJ

**Comment by oparoz** [comment]
Yes, Pydio is wasting bandwidth by downloading each preview at their max size and doesn't have a pan/zoom feature, but it does have some interesting features.

**Comment by oparoz** [comment]
Closing in favour of https://github.com/owncloud/galleryplus/issues/193
