### ISSUE TITLE
Mobile users should be able to "swipe" through photos instead of clicking on icons. [$5]

### ISSUE THREAD

**Issue by setnes** [owncloud/gallery#141]
Swiping photos with fingers is the expected user interface behavior for viewing photos on mobile devices.  It would be great if the gallery slideshow viewer could incorporate this feature.  An example project that does this well is PhotoSwipe.  There might be other ways to accomplish this though.

http://photoswipe.com/
##

**Comment by oparoz** [comment]
I agree. It conflicts with the zooming capabilities though, so that's one reason it wasn't implemented yet.
PhotoSwipe could be a solution. It needs to be tested as a replacement of Bigshot.

**Comment by oparoz** [comment]
So, Photoswipe can't be used yet, as described here: https://github.com/owncloud/galleryplus/issues/142#issuecomment-102802302

**Comment by oparoz** [comment]
And it doesn't mean it can't be implemented some other way. There are libraries we can use, but we need to make sure the one we pick doesn't interfere with the zooming control.

**Comment by oparoz** [comment]
Just a thought. It might be possible to detect a swipe on the bigshot container, but in order to make the effect work, we would have to load between 1 and 2 extra Bighsot objects so that we can swipe between pictures. I'm not sure that it's ideal, especially on iOS which is very memory constrained and crashes when running out.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#30
