### ISSUE TITLE
Would it help at all to look at this competitive product?

### ISSUE THREAD

**Issue by b1ggjoe** [owncloud/gallery#143]
Hey Everyone,

I know that a lot of folks are working on improving 'GalleryPlus' and getting it ready for primetime and etc.

I'm not a coder and I don't script, but I thought I would submit this quick note just in case it helps at all:

There is a competitive product to ownCloud that is VERY NICE with a gorgeous UI. It's called 'Pydio'.

Pydio has an excellent way of providing 'previews' for both images and videos. It doesn't do it exactly the way that we're trying to do this with GalleryPlus, but it's pretty smooth nevertheless.

Anyway, in case it helps at all, here's a link to the Demo Page:

https://demo.pyd.io/
1. - Just login with username: demo  |  password: demo
2. - Once you login, on the left, underneath 'Workspaces', click on 'Personal Files'.
3. - Once you do this, the folder's contents will be shown on the page on the right-side.
4. - Double-click on the folder called 'Images', which should be the third folder down from the top.

Once you're in this folder, you'll notice a few things:
- It shows all of the images in this folder as a 'List'.
- Each time you click on an image, a 'thumbnail preview' is shown on the far right.
- Even still, you can go to that image on the far right and click on the 'Preview' button. This will then show you an enlarged preview of the image.
- Above the image on the far right, there are also a few menu options, such as 'Sort By', 'Display' and 'File Info'.
- Under 'Display' you can also choose 'Thumbs (short for Thumbnails).
- When you are looking at the thumbnails, to the left of the 'Sort By' option, you'll notice a new option called 'Thumbs size'. If you click on here, it will present you with a slider where you can easily scale the size of the thumbnails, up and down.

Anyway, since everyone is working hard with trying out different ideas, I thought that it would help if you took a look at the way this product was implementing their version of their own 'Photoviewer'.

Hope this helps,

BJ
##

**Comment by oparoz** [comment]
I know about and like pydio, but I think you should post this in core, because this mostly concerns the Files app, even if Gallery is responsible for the slideshow. Files would benefit from the display setting and the Info panel (I think it's coming in 8.2), but the thumbnail zooming and small preview come at a prize: It increases the download size of images by a factor of **30**, which is a problem on mobile.

There are also fundamental differences between pydio and oC. We have apps and the goal of an app is two-fold:
1. Add actions to the Files app
2. Provide a unique view

Maybe we could provide media file information and preview content for that info panel once core has it and if the app doesn't already do it.

Ideas we could "steal" for the Gallery view
- Thumb resizing? Not sure it would be useful in the Gallery
- Anything else?

**Comment by oparoz** [comment]
Sidebar WIP https://github.com/owncloud/core/pull/16414

**Comment by jancborchardt** [comment]
I know Pydio since a long time. And honestly, I find the UI too confusing. It has too many elemtents, oftentimes just at places where there was space instead of relevant positions. For example the »delete« and other actions which are up top all the time and not at a relevant position next to the file.

The sidebar as @oparoz mentioned with details and share stuff and file activity we’re working on it at owncloud/core#16414

@oparoz please no thumb resizing. It will make everything more complicated and is really an unnecessary function. We could add a whole bunch of stuff based on »what is possible« but we need to decide on what makes sense, is feasible, and pragmatic. We also need to keep in mind that people prefer a stable and trustworthy product over something rich with arbitrary features _any day_.

**Comment by oparoz** [comment]
@jancborchardt - I do think that the possibility to switch between list, detail and thumb view is great though, even if badly implemented in pydio (no name on thumb folders). That's a standard feature on most file browsers.
But like I said, this is a feature request for core (and it might already exist)

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#31
