### ISSUE TITLE
Image will not be loaded though the folder is shared

### ISSUE THREAD

**Issue by fin0** [owncloud/gallery#149]
### Steps to reproduce
Login into your owncloud.
Share the link of a folder containing one or more images.
(If you want you can logout/change browser now)
Open the link of the shared folder.
Click on the gallery view.
Click on one picture.
Copy link of this picture and paste it to a new tab or another browser.

### Expected Result
The picture should be shown in fullscreen since the picture is in a folder which is a shared one.

### Actual Result
Owncloud seems busy loading the picture but will not finish.

### Version
ownCloud 7.0.4.2

**Comment by oparoz** [comment]
Does it happen with all files? Is encryption enabled?

What happens when you load this link per example (which would be the case you're describing)?
https://oc7demo.interfacloud.com/index.php/apps/galleryplus/public?token=312b038d3e70877199a4d66abf37bdd0#Photoshop/restaurant_flyer_A5.psd

The picture should load in full screen and you should be able to zoom in.

**Comment by fin0** [comment]
Thanks for following up! Your example is working..do you have any ideas where the problem could be located? It seems to be an issue of the server since the problem is reproducible on different systems.

You are using another app which is replacing the standart-gallary, right?

**Comment by oparoz** [comment]
It's very difficult to say. Are you using the master version from this repository or the app which came with your ownCloud? Lots of things were fixed in the past 6 months.
I don't know if you're familiar with routes, but it could simply be that the URL does not convert into a viable route somehow and so the backend doesn't have the information it needs to load the preview.

The good news is that it should be fixed in the next release of the gallery app or the one after that.

**Comment by fin0** [comment]
I got the current version of owncloud from the website without any additional apps. It is not a big problem for me so I can wait a little bit, anyway, thanks for the insight! :)

**Comment by oparoz** [comment]
Closing as this is working in Gallery
