### ISSUE TITLE
Feature Request: Lazy load thumbnails by viewport (in files app)

### ISSUE THREAD

**Issue by theCalcaholic** [owncloud/gallery#170]
**Problem:**
Consider the following scenario: I have a folder with 1000 pictures and I'm looking for a certain one which I know to be somewhere at the end of this folder. Unfortunately I cannot see any thumbnails of that lower section until all thumbnails above have been loaded.

And even worse, I can't even delete or download files until all thumbnails are loaded (might be an issue with the files app though)

**Suggestion:**
The image files could be given a default thumbnail which then gets replaced using javascript but only (or starting with) for those images which are in the current viewport.
This would reduce the performance issues quite a lot and give the user a smoother experience.

**Comment by oparoz** [comment]
Actually, you problem is easily fixable. You just invert the sorting order and you'll get the pictures which sit at the bottom of the folder, but it may be a problem if you're looking for picture number 600 per example.

But your problem seems to be with the Files app, so you should file your issue there.
Gallery is only responsible for the large previews/slideshow.
