### ISSUE TITLE
Sorting by date does not honor EXIF information

### ISSUE THREAD

**Issue by edivp** [owncloud/gallery#171]
Is there no support for EXIF metadata when sorting by date? Or am I missing something? EXIF module is enabled in my PHP (Debian wheezy).

**Comment by oparoz** [comment]
You're correct, this is by design since the EXIF header is only available in JPEG and TIFF and since we don't have any other meta data we can use.

We need this to be implemented before being able to sort using the date a picture was taken.
https://github.com/owncloud/galleryplus/issues/101

In the meantime, we're using the date a file was uploaded.
