### ISSUE TITLE
Add a busy spinner while loading the next/prev image

### ISSUE THREAD

**Issue by mightycoco** [owncloud/gallery#172]
Add an indicator, that an image is loading (usefull for large images/slow networks/slow servers) in full-view mode or slideshow

**Comment by oparoz** [comment]
I don't understand your request because there is already a spinner in the slideshow.
It shows up when you first launch the slideshow and every time a new pictures is loaded.

**Comment by mightycoco** [comment]
The icon shows only up, when I first launch the slideshow. If I click prev/next buttons the current image stays in view until the new images is displayed.
The spinning icon is defined as a background image in the #slideshow div and is not visible as long as an photo is shown.

I'm on the current main branch and just checked again after doing a git pull (and clearing my browser cache)

**Comment by oparoz** [comment]
Which browser are you using?
I've tested on Firefox and Chrome and the current picture is discarded before the next one is loaded, so the spinner is shown. (It's not apparent with small pictures because the next one will already be preloaded.)

Do you have any errors at all in the browser's console? (F12)

**Comment by mightycoco** [comment]
- Tested on latest chrome (43.x) and IE11
- I have disabled the default gallery plugin and only enabled GalleryPlus
- There are 2 errors in the debug console, which might or might not be related. They ONLY appear when opening the slideshow the first time (without reloading the page)
1. Uncaught TypeError: Cannot read property 'images' of undefined (gallery.js:306)
2. Uncaught TypeError: this.currentImage.bind is not a function (slideshow.js:79)

The files are /apps/gallery/js/gallery.js and /apps/gallery/js/slideshow.js - should they even trigger, when the gallery app is disabled?

gallery.js:

```
305:        var album = Gallery.albumMap[albumPath];
306:        var images = album.images;
307:        var startImage = Gallery.imageMap[path];
308:        Gallery.slideShow(images, startImage);
```

slideshow.js

```
78: jQuery(window).resize(function () {
79:     this.fitImage(this.currentImage.bind(this));
80: }.bind(this));
```

Actually the sticky photos while loading the next is a pretty cool feature - if there was a loading indicator ;o)

**Comment by oparoz** [comment]
OK, so for some reason, Pictures is still being loaded in your setup. It's either due to a PHP or browser caching issue.

I'm sure once the app is really disabled, your problems will go away. The code you referenced does not exist in Gallery.

I'm keeping this open until you can confirm not getting the problem any more or if there is still something to be done.

**Comment by mightycoco** [comment]
Enabling and disabling the pictures app solved the issue. Somehow both where loaded (gallery and galleryplus) even though only galleryplus was enabled (and accessible via the UI)
