### ISSUE TITLE
Make "newest first" the default sorting order for albums

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#197]
Anybody feels strongly against it?

@libasys @demattin @setnes @jancborchardt 
##

**Comment by libasys** [comment]
you are the maintainer, that is your choice! ;)

**Comment by oparoz** [comment]
I'm neutral ;) and listen to my trusted advisers :)

**Comment by libasys** [comment]
I'm neutral, also! what is the default behaviour, if you open a folder on your desktop pc? Should the same as the files app!

**Comment by oparoz** [comment]
A desktop and the Files app use A-Z, but they're not used to show pictures.

**Comment by libasys** [comment]
Look you have your arguments! ;)

**Comment by setnes** [comment]
I prefer oldest first for photos in a directory.  As long as I can override the default with gallery.cnf though I'm happy.  

I understand why you would sometimes want newest first, but I think about the "directory of vacation photos" use case a lot.  Starting in reverse order on things like that is unexpected.  On the flip side, a directory of photos receiving frequent updates (photostream directory) might make sense the other way... but certainly wouldn't be unexpected if the default was oldest first.

**Comment by jancborchardt** [comment]
Many common picture apps do newest first: Android photos, iPhoto, Shotwell (Ubuntu), … – so that’s the expectation.

Alphabetically really does not make a bunch of sense for pictures since they are often just named like »IMG_20453*« – and then the modified date can be used for the same sorting.

**Comment by jancborchardt** [comment]
Facebook, Twitter and Flickr (arguably the biggest photo services out there) do it like that as well.

We shouldn’t look for file managers as benchmark when we want to design photo software. ;)

**Comment by oparoz** [comment]
Going once!
Going twice!
Sold!

**Comment by jancborchardt** [comment]
:D :money_with_wings:

**Comment by deMattin** [comment]
@oparoz: You have to count up to 3!!! ;))
First, I have to say sorry, not having enough time for testing at the moment - too much work for too less money ...

Do you really think, it is a good idea, to sort gallery on default a different way than files app?
1. A different (default) sorting order will be irritating, if you switch from files app to gallery app.
2. Web Owncloud and owncloud apps are browser (desktop) apps and not (separate) smartphone apps. They can be used on tablet or phone, but I think, that's not the most use case. For tablet and phone, you have a separate owncloud app designed for this use case.
3. Picture folders in owncloud don't contain of photos named a more or less good way by phone. I think, they are mostly collections or archives maintained and so mostly/often (re)named by the user. So naming of the pictures DOES often make sense for anybody, who maintaines his data.
4. Sorting pictures or graphics that aren't photos on creation date? Sounds REALLY not to be a good idea!
5. Sorting by file date (not meta data!) and you edit/rotate/crop photos? Sorting will become weird.
6. If you want to have different sorting order, it is customizeable

Especially point 1, 4 (and 5) leads me to the opinion, to let it the way it is -> alphabetical order on default.

Or another approach - but I don't know, if it is to complicated:
Is it possible, to inherit the actual sorting order of files app, if you switch from there?
This will be, what user would expect if he switches from files app, I think.
And if not using switch from files view and starting gallery with the menu app switch?
To say again: Owncloud gallery is no smartphone app. So how do desktop apps behave? I only use/know ACDsee pro, Irfanview, Windows default picture folder. You are able to set anything - but default is always alphabetical!

BTW as an example:
In my owncloud I have overwritten sorting on 2 folders with subfolders to sort reverse by name.
I always (re)name photos by date, so here also reverse date sorting would do it - but only if I didn't edit them (roatete/crop/... whatever) - so name sorting is in my case also for photos more reliable.
But all other folders and subfolders with pictures in my own productive used owncloud space (23GB of data) are definitely better sorted alphabetically! There are many graphics folders and folders with named scans.
And I don't think, other cloud spaces look very different than mine:
You have some photo folder, where different sorting may or will have been wanted but many other folders also containing pictures, where date sorting will be more than weird!
And for the photo folder(s) you have the .cnf-way. And if you have one main photo folder with many sub folders, like it often will be, it's only 1 cnf-file with inherit flag!

(my english seems to get worse every day - but I hope you get my arguments ... ;))

**Comment by setnes** [comment]
A few points...

To say that a user can control file order by adjusting the filename is equivalent to having the user adjust the file dates to match the metadata (this is what I actually do).  I actually prefer date ordering over filename ordering for images.  Neither are perfect.

You can override whatever the default ordering is by using a gallery.cnf file.  Only one is needed at the top level if you want to control the default order on all subdirectories.  I do this too, so changing the default wouldn't really affect me.

The photo sharing apps mentioned as a comparison are really photostream type sites with stuff like RSS feeds.  They're really more of a bloggy type thing than a photo _album_ type thing.  Other sites that serve directories of photos might have different default orders...  (dropbox, picasaweb, etc)  It doesn't matter what they do though.  OwnCloud is supposed to be better than those sites anyway.  :)

I still think there are two competing use cases.  One is a directory of photos served up as a photostream.  New photos can be added frequently... and the newest should be on top.  The other use case is serving up photo albums.  A directory for somebody's wedding...  A different directory for a vacation to New York...  Another directory for a family reunion... etc.  These album directories make sense oldest image first as that is how you would probably want to flip through the photos.

Which use case is more common?  I think sharing directories of organized photos might be more common than a photo stream...  but we're only talking about the default.  The content owner already has control using the gallery.cnf file.

**Comment by jancborchardt** [comment]
> 1. A different (default) sorting order will be irritating, if you switch from files app to gallery app
> 2. Sorting pictures or graphics that aren't photos on creation date? Sounds REALLY not to be a good idea!
> 3. Sorting by file date (not meta data!) and you edit/rotate/crop photos? Sorting will become weird.

@deMattin 
- 1. Why that? I don’t think so. It’s different use-cases.
- 4. Um, yes it does? I want my designs to be sorted by date so I can easily find stuff again and view revisions pretty much chronologically. It’s always inside a folder, keep that in mind
- 5. We just need to decide here if the edited photo should inherit the date of the original, or be a fresh one. Nothing weird about either case imo, we just have to decide. Android makes the edited image inherit the date, so it’s sorted just newer than the original – good call.

> Other sites that serve directories of photos might have different default orders... (dropbox, picasaweb, etc)

@setnes well, Dropbox sorts by newest first as well. There you go.

**Comment by jancborchardt** [comment]
Also @setnes I think you misunderstood:

> I still think there are two competing use cases. One is a directory of photos served up as a photostream. New photos can be added frequently... and the newest should be on top. The other use case is serving up photo albums. A directory for somebody's wedding... A different directory for a vacation to New York... Another directory for a family reunion... etc. These album directories make sense oldest image first as that is how you would probably want to flip through the photos.

Folders are not going away. This is just about the default sort order.

**Comment by setnes** [comment]
I know folders are not going away.  Folders are really all that there is.  That is kinda my point.

I see different orders required for different uses.  I'm  OK with any default as long as I can override it.  My _opinion_ would be for oldest first though.

**Comment by jancborchardt** [comment]
@setnes yeah, this is about the default which the majority of people will not change. Personal preference and opinion has to take a step back in a design decision like this.

**Comment by deMattin** [comment]
I'm also talking about what the user would expect if switching to pictures view.

This is not only a photo app - it's a universal picture app for photos, graphics, designs and many more.
So I really think anyone would expect name sorting as default.
It's more like switching the view in windows file explorer with filtering out non picture files.

I also know many users in job, who have reverse date sorting as default on files in explorer. But no one would expect this as system default!

@jancborchardt: Maybe sometimes sorting a folder with a bunch of graphics by date may make sense, but if you are having let's say100 files in a folder and you see one version of a file at first than at 10th and at 34th position ... I don't really think, that's the way you expect it ON DEFAULT!
Visual searching version 2 of a file named "file-b.gif"? Nearly impossible! In files view it is the 5th file and switching to gallery for visual checking, it's not there any more ...
Visual searching manual backup of a file named "file-bak.gif"? Nearly impossible!
And this is even more an issue, because you only see file names by mouse over!
Ok, just some resorting clicks to resort and why is that neccessary? Because the app default sorting adresses mainly mobile photo snapshot directories.

And file date editing is a thing, not anyone is able to do. You (re)save the file with a desktop app and you have it sorted at another place in view. Not weird for default behaviour? I think, it is. 
I'm absolutely sure, that we will get issues in git, where user will complain about unlogical default sorting order. Even more, if settings will be "hidden" in a pulldown and not be visualized by an icon.

If we would have been talking only about photos, I would have said ok to sorting reverse by date on default - although it is not my prefered default sorting solution also for photos.
And then we should rename it "photo viewer"!
But giving the gallery defaults, that only work for some users, that are ONLY viewing photos with unstructured names with it, isn't a good idea, I think.

Every sorting order has its use cases and so it's a good thing, to be able to switch between them ON DEMAND. And it's even better, to set different individual folder defaults.
But here we are talking about the app defaults. This shouldn't target only (some) photo view preferences.
And I'm sure, if you ask users, what they EXPECT by a gallery app (not a photo app), the majority will say "like files app" or "like a file explorer on a desktop system".

**Comment by oparoz** [comment]
Thank you all for your feedback!

I think we need to make the distinction between the thumbnail view in the Files app, which unfortunately doesn't exist yet and the presentation of media files in Gallery.

In the Files view, we should be able to ask for the thumbnail view and get the files arranged in a grid and with larger thumbnails than when files are in a row. The sorting order would be the same, the default being alphabetical. It would also be great to automatically get that view when the app detects that the content is mostly media files. Having such a mode would be great to share "business" content (graphics, presentations, fonts, etc.). Large thumbnails make it easy to identify what is what and a photowall doesn't necessarily add much value.

In order to be able to decide what the default sorting order should be **today**, we have to answer these 2 questions:
1. Should we act as replacement for the Files' thumbnails view while we wait for its implementation?
2. Do we consider Gallery a photo app which should present content like Flickr, Photos or the mobile phone's camera folder?

Regarding 1), I started working on Gallery+ because I needed to be able to see larger thumbnails and because my files were in various formats that I would need to be able to share online without having people guessing what Corporate_bauhaus_v2b.psd looks like.
The Files app in 7.0 with it's default view and media type support didn't cut it.

If more users like me have started to use the app that way, then modifying the sorting order now, when there isn't a viable alternative, except by fiddling with configuration files might not be the best thing.

Now on to 2). I don't archive my photos to ownCloud, but I organise my albums like in a gallery, by theme, artist, etc., so newest first would do nothing for me, but I don't think I'm the typical ownCloud user and neither are my clients.
So if for most people ownCloud is used for photos and comes with Gallery, I think it's reasonable to expect it to present them like the big brands, newest first.
I don't exclude adding more "views" to Gallery if needed, like a portfolio view with large thumbnails, etc., but by that time, we should have user preferences which will make it easier to modify the default sorting order.

So my position would be to maybe keep it as-is for the time being and once the Files app gets its thumbnails view, then re-assess and follow what conferences, polls, large clients, etc. tell us about the use of the app.

_ownCloud should have an official poll app to collect feedback from users when admins enable it... Just push a question a month, get people to register to get more that one in case they're interested in providing feedback. Nobody will willingly come here to tell us about their preferences._

**Comment by jancborchardt** [comment]
Folks, I appreciate the input but this is way too big of a bikeshed discussion over such a small thing. We need to make a cut and decision here.

As I mentioned basically all other popular gallery apps do this, so let's simply use date sorting (newest up top) by default and see how it works.

**Comment by jancborchardt** [comment]
@oparoz the feedback mechanism you talk about will have a heavy bias towards people who care to vote. Just like Github issues comments have a very strong bias towards techies like us who are registered here. ;)

**Comment by oparoz** [comment]
I agree that it will be one characteristic of the sample, but that's not the variable we're looking at. In order to know if it's representative we would need to know a bit about who's answering, but that's tricky. Assuming the poll is not limited to a certain category of users, it should give us an idea of what is going on, short of visiting unis, businesses and people at home :)

**Comment by deMattin** [comment]
1. I support a voting possibility. This way we don't get everybody but maybe more than 3-4 people talking here. But I agree, a poll won't be easy. Because you have to give the user the main arguments pro and contra to get a good personal decision.
2. @jancborchardt: It's no good style in a discussion to say: "It's enough - follow my opinion and do it like I suggest!" Even more, because your argument doesn't hold. You stay on comparing photo smartphone apps with gallery on oc, which does have other and more functionality, service and use cases. And btw a usual decision in a discussion with no real good solution for all is to leave it, as it is!
   But I agree with you, that here's no progress in discussion any more. 
3. I follow @oparoz - also with the point of view, to possibly switch gallery more to a photo app later, with whatever defaults you prefer, IF the usecases he mentioned and I'm also targeting in my "epic statements" are covered by files app.
   I didn't know, that giving a bigger thumbnail view in files app is in planning state.

@jancborchardt: We seem to have very different stances on some topics and I thought about it.
I think, we both have the same target: giving best experience in using oc to the common user.
My individual and personal preference is REALLY not the main intention, if I discuss here.
Maybe it's caused by the "normal" usage, we aim at.
For me, my oc users and also the majority out there oc is mostly used as a desktop browser app with mouse control (in my opinion) and maybe you target it more for touch devices.
There never will be a solution, that fits both a real good way. So also Microsoft with windows 8 and even more on 10 mess with both and noone really likes it.
If even Microsoft doesn't get it really good, it will be harder to owncloud with it's hand full of developers.
As I know, that there's no real solution for both with 1(!) frontend, the only thing I hope I can address to you, is to show another point of view and that you think emotionless about it's advantages and disadvantages.

**Comment by jancborchardt** [comment]
> You stay on comparing photo smartphone apps with gallery on oc, which does have other and more functionality, service and use cases.

I did not only compare smarthone apps. Look at the web versions of Facebook, Twitter, Flickr, Dropbox, 500px – all the common photo gallery services. And iPhoto, Shotwell are desktop apps in case you didn’t know.

**Comment by deMattin** [comment]
As you said: "Photo Gallery service".
Gallery in OC is no or not only a PHOTO gallery service!
Again and again the same ... frustrating ... :/

**Comment by oparoz** [comment]
I think the fact that historically "Pictures" was an app which was showing pictures from the Photos folder has a lot to do with the perception that Gallery should behave the same, but it has evolved.

I've filed [this](https://github.com/owncloud/core/issues/17357) in core in order to fill one of the gaps between the Files and the Gallery apps. That won't solve everything, but should help fill some use cases.

**Comment by NuxRo** [comment]
Hi,

Any idea in which version to expect "newest first" by default or at least have it save the sorting I chose?

**Comment by oparoz** [comment]
> Any idea in which version to expect "newest first" by default 

My crystal ball says 2017. But track this issue: https://github.com/owncloud/core/issues/17357

> at least have it save the sorting I chose

It's in the doc: https://github.com/owncloud/gallery/wiki/Gallery-configuration#album-configuration

**Comment by NuxRo** [comment]
Thanks. I guess there's no config option to do the same for the files, too?
It's just so annoying..

**Comment by oparoz** [comment]
I'm sure an app could be written to hijack the sorting order in the Files app

**Comment by jancborchardt** [comment]
See https://github.com/owncloud/core/issues/20836#issuecomment-162800162 for the relevant discussion. Remembering the sort order will take care of this and should be fixed in core, not as an app.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#49

**Comment by Relequestual** [comment]
Did this get fixed in owncloud? If so, which version? I can't seem to find the resolution, and closing the issue because it's migrated to nextcloud doesn't feel like the right thing to do imo =/
