### ISSUE TITLE
Out of memory for bigger pictures

### ISSUE THREAD

**Issue by Bodenseematze** [owncloud/gallery#210]
When I try to view a directory which contains JPG pictures which are bigger than about 4MB it stops building thumbnails and the waiting spinner turns round forever.
When I choose a base directory in which sub directories with bigger pictures are, I only see the spinner - no subdirectories are visible.

When I then have a look in the owncloud log, I see the following line:
Error   PHP     Out of memory (allocated 93847552) (tried to allocate 23040 bytes) at /home/www/owncloud8/lib/private/image.php#489

I currently use OwnCloud 8.0.4 with galleryplus v12 on a debian based webhosting (apache 2) which allows me 512MB RAM for PHP scripts.

What also seems to be a bit strange: the above total mermoy bytes ("allocated 93847552") are always the same (not the "tried to allocate" number - that differs)!

**Comment by oparoz** [comment]
Hello and thanks for the report.

It seems your host has caped the memory available to PHP to 90MB and not 512MB. Check with phpinfo() and ask them about it.

**Comment by Bodenseematze** [comment]
I checked with phpinfo() - which parameter shall I post here?
The following values are shown as "local" and also "master" values:
  post_max_size is  200M (set by me)
  memory_limit is 512M
  upload_max_filesize is 200M
I don't see any reason, why it should cap at 90MB...

BTW, it's PHP 5.6.9 if that matters...

**Comment by oparoz** [comment]
Is the 512M limit the same for both local and master?
Do you have something like Suhosin installed maybe?

I'm going to close this as this is a PHP config problem which blocks a core functionality, but we can still talk about it.

**Comment by Bodenseematze** [comment]
Yes, as already told above - the limit is for both, local and master.

No, Suhosin is not installed.
What else can I post on information to find out what's wrong?
(I don't want to put my phpinfo page as attachment - there seems to be too much sensitive information which I don't want to post on a public accessable page)

Why do you think it's a PHP config problem?
My provider tells me (of course) there's no configuration problem at their side and that it must be a problem of the software :-(

If you sent me your personal E-Mail I would sent you a link to the phpinfo page if that helps...

**Comment by oparoz** [comment]
Sorry, I know it doesn't feel good to be bounced around, but your PHP is given a limit somewhere which prevents it from creating JPEG previews.

You should get the same problem in the Files app. Thumbnails for those files should be blank.

You can reach me via the email address on this page: https://github.com/interfasys

**Comment by oparoz** [comment]
I've just done some reading and your host (or the default value) is probably limiting the amount of memory available to Apache processes. On some Debian setups, GD is not limited by PHP limits, but by Apache or the kernel.

Try to modify your RLimitMem value.

**Comment by Bodenseematze** [comment]
Your partially right - I don't see thumbnails for those files in the Files app.
But the error message in the log is not shown for that and (big difference to galleryplus app!) it continues building the thumbnails for the other files...
...the galleryplus app stops working after that error - and I don't even see the following files and sometimes (in upper directories) I don't see anything (because in one of the subdirectories it gets that memory error).
Couldn't the app skip that file when getting that error and continue with the next one?

BTW, in the Files app I'm also unable to open such files - I get a "Error! Could not generate a preview for that file. Please go to next slide while we remove this image from the slideshow".

Regarding the RLimitMem value - I'll ask the provider for that (what does "GD" mean?)

**Comment by oparoz** [comment]
I'm pretty sure the error is logged, in one way or another, because you're not getting the thumbnail.

The Files app is highly inefficient in the way it asks for thumbnails, it makes a separate HTTP request for each one of them. But at the same time, it makes it resilient, because if one fails, the whole app doesn't.
In Gallery, I can catch most errors, but a fatal error such as this one can't be caught. The process which streams thumbnails back is terminated and the view is never notified.

If you load the slideshow, you should be able to browse through all the pictures, except the ones which can't be previewed, as you've described.

GD is the bundled extension which manipulates images in PHP. 

I've looked at your phpini and didn't see anything unusual.

Things I thought about, but which won't work.
- Test memory needed to create image
- Timeout for thumbnails

I'm open to suggestions if you think you can solve this problem.

**Comment by Bodenseematze** [comment]
It's now solved :-)
My provider changed some mysterious internal flag (he didn't / didn't wanted to tell me which one) and now the thumbnails are shown and no more "out of memory" logs!
Thanks for your help...

Nethertheless, I'd prefer robust applications that don't stop on "bad" files and continue working - even if they're inefficient...
Maybe you could change the app behaviour that it's not as efficient as it's now with better "support" for bad behaving images / PHP errors?
I'm sure that most webhosting installations only have 128MB available and that the "out of memory" error is common for them!?

Maybe you could (mis)use PHPs register_shutdown_function to set a some marker at which file it stopped?

**Comment by Bodenseematze** [comment]
e.g. like here:
https://github.com/Seldaek/monolog/blob/master/src/Monolog/ErrorHandler.php

or a description here:
http://stackoverflow.com/questions/27238473/how-can-i-catch-all-errors-in-php/27238474#27238474

(never tried it myself :-)

**Comment by oparoz** [comment]
Glad it's sorted :)

I prefer robust apps as well, but this is really a case of solving a problem which will affect few people by degrading the experience for most, so I'd rather not change it.

register_shutdown_function() can't be used, because PHP is out of memory already, so it can't process anything else.

**Comment by Bodenseematze** [comment]
I'm not sure if it only affect few people - I think there are a lot people try to use OwnCloud at a webhoster (of course I would prefer to use it on a server where I've full root access - but that's for personal too expensive for personal use)

About register_shutdown_function:
You could use a (very bad) trick and allocate some memory at startup which you can then free in case of an error ;-)

public function initErrorHandler()
{
    // This storage is freed on error
    $this->memory = str_repeat('*', 1024 \* 1024);

```
register_shutdown_function(function()
{
    $this->memory = null;
    if ((!is_null($err = error_get_last())) && (!in_array($err['type'], array (E_NOTICE, E_WARNING))))
    {
       // $this->emergencyMethod($err);
    }
});
return $this;
```

}

**Comment by oparoz** [comment]
OK, please create a new issue as a feature request, but it would be great if you could provide a PR :)

**Comment by Bodenseematze** [comment]
Sorry to be such a noob - but what das PR mean?

**Comment by oparoz** [comment]
Ah, sorry, since you pasted code, I assumed your knew :D 

A pull request. That's where you fork this repository, apply your changes until you're satisfied and then ask for your changes to be merged back.

Ideally, you do everything using git tools, but it's also possible to just clone this repo locally, make changes and then edit the code on Github. It will create the fork for your and offer to create the PR as well.
