### ISSUE TITLE
Make the slideshow themable

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#233]
_User suggested_

I think it's a valid claim since the rest of the app is using the global theme. Not sure how to implement this.

**Comment by oparoz** [comment]
@jancborchardt - If you could spec this since you worked on the example theme.

**Comment by jancborchardt** [comment]
What exactly did that person refer to by making it themable? The icons can already be freely replaced by just putting new ones with the same name in the theme. Then all that’s left is the background, and I would  really rather not make that themable since black is the standard color for a slideshow. If someone wants to theme that they can simply overwrite the CSS.

**Comment by oparoz** [comment]
Here is the original request: https://github.com/owncloud/gallery-old/issues/108

Maybe this was a problem on older releases?

**Comment by jancborchardt** [comment]
Can’t access the issue because I guess @DeepDiver1975 closed the issue tracker so people don’t submit any new issues there?

In any case I guess yes, this might have been a problem in older releases. I consider this fixed. If anyone has further requests, they will open them.
