### ISSUE TITLE
Add full screen button in slideshow

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/gallery#252]
It would be nice to have a full screen icon that you could click in the lightbox mode.
##

**Comment by oparoz** [comment]
@jancborchardt

**Comment by jospoortvliet** [comment]
I would say that every browser has a built in full-screen button. Shortcut is F11 in almost every case. Works great with the slideshow...

**Comment by pascalBokBok** [comment]
@jospoortvliet How do you hit F11 on a tablet?
Besides, lot's of people don't realize that they can do it. It's not just a gallery for h4ckers ;-)

**Comment by deMattin** [comment]
F11 is not really a "hacker-shortcut" (... maybe for this class of only-tab-users, that don't know PCs at all :wink:).
We discuss in other threads about real good and sometimes/often needed setting options, that possibly will not be implemented because of an additional needed button and this lame "full-screen" should get a button only because Tablets/Phones don't have a shortcut for fullscreen?!

It's really a problem - you never will get a good app for "real" PCs/Browsers and Tablets/Smartphones in one GUI.
If you design a web app for Tabs/Phones and PCs you will loose features and possibilities on one of both or you have to reduce features for both.

Owncloud UI is a web-app for real browsers and not for phones (in my opinion). But it works on both phones and PCs.
So in my opinion Webview of owncloud should be **optimzed** for "real" webbrowser and for optimized view on smartphones/tabs there's the owncloud app!

There are some good features in owncloud not implemented and preset settings, that are worse for PC but needed for fingerfriendly usage because of this damn phones compatibility and forced simplicity for users, that are only able to point and click on phones with their big fingers.

But maybe someone has a solution with double click or click and hold or whatever ...

**Btw: You know the _"hacker-trick"_ in chrome for android (works similar in safari iOS) that tells the browser to launch the page fullscreen when the user has added it to his home screen using Chrome for Android's "Add to homescreen" menu item?**
The owncloud web app then is launched in full-screen "app mode".
This way you get rid of mobile browsers address bar and have a fullscreen view!
And this is also usefull for the other apps in owncloud and owncloud web app has the look and feel of a smartphone app.

**Comment by pascalBokBok** [comment]
The world is full of aunts, grandpas and people who don't want to think to use a computer. Owncloud does not get more traction by being a less attractive product for them.
BTW. Put the special buttons in an expand-menu like everyone else and your browser.
1337 greetings

**Comment by deMattin** [comment]
There are two philosophies:
1. Give features, give options and possibilities. That will lead you to (additional) settings, that not everybody will understand or need.
This is how every more professional app works - even in the Apple world!
2. Make everything as simple, that everybody can use _everything_ and don't implement features for people, who want to have more or like to work another way.
-> The developer always knows, what you need and what is good for you! This is, the let's call it "the Apple iOS way". ;)
And this is (sadly) also the philosophy of web gui of owncloud: simplicity and as less settings, options (and buttons) as possible and optimzed for touch devices.

No user has to be forced to use settings but in my opinion he should get the possibility.
So good defaults of presets, that anybody can use the app but for **all** features you have to know more than the first intuitive usage leads you to.
If a user doesn't want to go in deep, he should be able to use the app but as a result won't get all possible features.

This forced simplicity in owncloud requires to know even much more about the backgrounds and you really have to "hack", if you need more features or other presets (css/php/js hacking, own templates, git, additional apps and so on...)

But in this case:
If a user doesn't know a basic OS feature (web app view of browser sites via link on startscreen), he won't see a fullscreen owncloud but despite of this can use everything. Even grandpa can use it without any problems without fullscreen - probably he won't miss it at all!
And if you tell him, how he can get rid of an address bar in often used websites and make a website to a simple looking like smartphone app, he will like owncloud, other websites and his touch device even more. ;)

Owncloud gui designers want to avoid buttons and settings as much as possible.
It would be a bit absurd to give an unneeded and some sort of redundant fullscreen app button, but on the other hand don't implement more "professional" settings because they would need a setting screen and/or additional buttons.

**Comment by jancborchardt** [comment]
Honestly I’m not sure if it’s needed. Popular photo sites like https://flickr.com and https://500px.com do it, but Facebook and Instagram don’t.

I’d say we leave it for now.

> No user has to be forced to use settings but in my opinion he should get the possibility.
> […]
> This forced simplicity in owncloud

@deMattin there are plenty of more complicated open source options if you prefer that. ownCloud aims to be a real open source alternative to proprietary apps, meaning it’s usable for more regular people who are not hackers. If you like settings so much then you can just write apps for them yourself, but trust me that the majority of people do not care.
(Besides, 50% of people are women so »users« should not be referred to as »he«. Thanks!)

**Comment by deMattin** [comment]
@jancborchardt: You fully confirm may posting above with your "if you need settings, write an app..." - that is then the "maximum hacking" possible.
You can also say, if you are not my opinion, leave and write your own app - that's not the way a "community app" should work. Maybe I like to be the speach for the "advanced users" who want to get more opportunities. Without this feedback, you may think, they are not out there and owncloud users are only grannies, grandpas or technical not capable people with their iPads. ;)
But making enhancements or pulls here against your resistance is waste of time because you negate basically the need of simple or advanced customization.
We often confront with each other on this but I think, basically our thoughts are more similar in kind, that it sometimes seems to be.

And beginner users don't care, you are right. But I'm sure, I'm not alone or a very small minority, that wants or likes options or easy to be "hackable" or alterable presets. And users that are more advanced would like variables to be set easy in templates.
But I still hope, you have this in mind and possibly think of it in further development of GUI design. Basic variables with on it depending values instead of hard coding values are mostly no problem if you design or rework from scratch and have customization in mind.

And ... sorry, this gender speach shit is hard (and unneccessary) enough in german - I'm not able to handle this in english. And no really emancipated women cares about it.

Sorry, too much off topic... :/

So, on topic: No button for fullscreen. :+1:

**Comment by jospoortvliet** [comment]
Alternatively, we could simply enable fullscreen by default when the user starts the slideshow and close it when the user exits the slideshow. It makes total sense to me - if you want to view your pics in a slideshow, you want to view your pics, not all the other 'stuff' around it. How about that?

**Comment by Tramour** [comment]
@deMattin 
I am quite new to this "forum" and sort of like collaborative field of work (and definitely more reading and absorbing than actively participating).
But thru reading I really see your point of view. I am absolutely your opinion. To me it seems that some folks here have the say and all the others are obliged to share their views. Participation welcome as long as you follow the general guidelines. Innovation, new ideas, feature requests only acceptabe if they fit the master plan. Otherwise: do it on your own with your own app.
This is not a matter of what working expierence you have or what you studied but a field of ideas and dreams what might be useful or of essence to first of all one self and maybe the public.
Good basic settings are welcome but there are adavanced users and admins who want to be enabled to adjust this and that. 
This is to me the basic idea of this kind of collaboration. Bring forward your ideas and discuss it. But to generaly state that this is all not needed... This is obtrusive and patronising. 
And before I get a not-so-on-the-topic-comment for my English: I am sorry for all the mistakes I made.

PS: Don't worry, this was a one-time-comment and I see for myself that this is not the place for me or the way I see productive co-operation. I rather contribute to unoffcial apps. @deMattin I really admire your stamina and your will to have a different view. You were right: you are not alone.

**Comment by deMattin** [comment]
Automatic fullscreen view only in slideshow might be a solution.
I found this yesterday and it seems to be possible to get it only for smart devices - but his feature should have to be enabled **only** on small devices like phones or tabs and surely not on "real browsers":
http://www.html5rocks.com/en/mobile/fullscreen/

@Tramour: Thanks for your comment.
I really love the owncloud project and mostly understand the main collaborators intention or point of view better than it often seems to be - it's a hard work, they have to do and they have many things to observe. But I think, there's a way to design an owncloud for "simple" use(rs), advanced and "hackers" at the same time. And if the core team does have it in mind and considers the different usergroups and needs, it can mostly fit them all without a big additional effort!
And a big community is the best way to keep the project alive and progress it.
But without feedback they don't know the need and if you read in other public forums, former user/admin often simply complain about something and go back to google, dropbox or other.

**Comment by jospoortvliet** [comment]
@deMattin I agree with you when you say that there's a way to design ownCloud for both basic and more advanced usage - at least, often. But it is harder and you'll often need to think and discuss more. Going full-screen automatically is exactly the kind of solution for that - do the right thing automatically and you don't need a button, you're still simple, yet powerful. There will always be another 0.001% who is unhappy but that, really, is where a custom app comes in.

**Comment by deMattin** [comment]
Yes, and here's the point, where @oparoz and @jancborchardt should say something:
What do you think about automatic fullscreen for smartphones/tablets in slideshow similar or like it is described in http://www.html5rocks.com/en/mobile/fullscreen/ ?

**Comment by oparoz** [comment]
My problem with fullscreen on the desktop is that it's a "heavy" operation. It uses a lot of resources, disrupts the workflow if you're doing multiple things at once, etc. so I'm not sure a 100% automatic is the way to go.

On top of that, my philosophy is that if you make something automatic, you should offer a way to disable it.

Regarding usability in general. I've said many times that a good UI needs to cater for the needs of different categories of users. We need smart defaults and a way to alter the workflow.

## My proposal

### Desktop

I've seen a full-screen button in quite a few slideshow apps. Even Youtube has it. So I don't think having one would be a major UI issue.
- Go fullscreen when enabling the auto-slideshow
- If the decision is made in this issue to not show a button, offer the option to enable the button from the slideshow settings

### Mobile
- Always go fullscreen. Apps do it for multimedia content, so it won't feel unnatural to users
- Offer the option to disable the button from the slideshow settings. Not all tablets are limited to a single task at a time, so some people will want to disable that feature

### Settings

The way I see it, we can either have a list with checkboxes or clicking on the settings icon can reveal all buttons (disabled ones are half-transparent) and we click on them to enable/disable them. I like the 2nd option better as it's more visual and would probably work better on mobiles.

**Comment by jospoortvliet** [comment]
@oparoz good proposal. I think that you should go full-screen on enabling the auto-slideshow and that that is enough. It is pretty sure that people want that to be fullscreen and that the normal mode better not be... Their browser has a full-screen button anyway, in case people really want it - but I know many people don't even care about maximizing their window so I don't think it is a big deal.

Having the ability to enable a button in the settings - I don't object but I would propose to not have 10 settings for 10 different buttons you can enable and disable but have one setting for 'advanced UI' or something like that, which enable this and other 'extra' buttons (like the one for selecting background color for example). That keeps the settings simple, too. Not sure what @jancborchardt thinks about that...

**Comment by oparoz** [comment]
@jospoortvliet - I agree about trying not to confuse users :). We also have to think about temporary vs permanent settings. Right now, I've focused on permanent, global settings.

**Comment by oparoz** [comment]
@jospoortvliet @deMattin @Tramour @jancborchardt @pascalBokBok 

Everybody agrees that it's enough to enable fullscreen mode when starting the slideshow and that we don't need an extra button?

Desktops have keyboard and the F key already enables the user to go full screen.

**Comment by deMattin** [comment]
Users who don't know F11 on Desktop don't need or take care of fullscreen ON DESKTOP.
For Android and iOS Smartphones/tablets there exists the much better way and user experience to get the complete owncloud without browser address via a simple starter link.
So I see no need for a button on any platform.

Personally I would hate it, if gallery or any other browser app or website goes in fullscreen mode on my desktop PC without my explicit order - and calling a slideshow is _no_ order to call a fullscreen browser window!

On smartphones or tablets a fullscreen slideshow won't bother me.

**Comment by oparoz** [comment]
Ah, right, the goal on mobile is to cover the browser address bar... Then something would be required for mobile.

I think you misunderstood though, you only go fullscreen if you press play. I think it makes sense in that context, since you're probably not going to do anything else while watching the slideshow.

**Comment by deMattin** [comment]
You are right, I misunderstood. I thought, you were talking about just clicking picture preview and fullscreen showing of the picture.
For automatic slideshow after pressing play I agree and see now problem to force fullscreen.

**Comment by oparoz** [comment]
There is a PR to allow fullscreen mode when starting the slideshow
https://github.com/owncloud/gallery/pull/454

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#58
