### ISSUE TITLE
Strange error message when image cannot be loaded

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#257]
![capture du 2015-07-30 18-43-17](https://cloud.githubusercontent.com/assets/925062/8989271/611ba282-36eb-11e5-9c45-e7fbc94f9800.png)

> **Error!** Could not generate a preview of this file.
> Please go to the next slide while we remove this image from the slideshow

First, the part »while we remove this image from the slideshow« is wrong on several levels
- it uses »we«, which acts as if ownCloud is a person or group of poeple. Never ever do that.
- it says that the image will be »removed from the slideshow«. Initially I was afraid that the image would be removed. It’s way too much detail.

Intstead, we should simply show an empty content message similar to how we do for empty folders:

> pictures icon (I need to make a »broken« version of it but for now the regular version will do)
> **Image can’t be displayed**
> There seems to be an issue with the file
##

**Comment by oparoz** [comment]
I'm OK with the changes, but the image is really removed from the slideshow (not from the folder or cloud). Meaning that if you reach that point again, the image won't be displayed. It's sort of an emergency message, displayed when we were not able to look at all the images in the folder before launching the slideshow. The point was to let the user know that he won't be able to see it and won't run into the error again.

"We" is not that bad. It's used quite frequently by organisations or devs which take an informal approach to communicating with their users, but I understand if ownCloud does not want to communicate that way. The messages have to be in line with the communication policy and that's the reason I opened this: https://github.com/owncloud/gallery/issues/244

So I'll be waiting for your PR :) The string will have to be formatted differently because apparently it wasn't picked up by Transifex.

**Comment by oparoz** [comment]
I think this one should be changed as well
`I am sorry, but I could not find any media files at this location.`

**Comment by ghost** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#65
