### ISSUE TITLE
Class 'OCA\Gallery\AppInfo\Application' not found when installing from master

### ISSUE THREAD

**Issue by enoch85** [owncloud/gallery#268]
When installing gallery(plus) from master like this:

```
# Download and install GalleryPlus
                wget https://github.com/owncloud/gallery/archive/master.zip
                unzip master.zip
                rm master.zip
                mv gallery-master/ galleryplus/
                mv galleryplus/ /var/www/owncloud/apps
sudo -u www-data php /var/www/owncloud/occ app:disable gallery
sudo -u www-data php /var/www/owncloud/occ app:enable galleryplus
```

... the standard gallery app is still enabled, and galleryplus isn't activated.

When I the try to run the commands one more time in shell I get this in owCloud log:

```
Class 'OCA\Gallery\AppInfo\Application' not found at /var/www/owncloud/apps/galleryplus/appinfo/app.php#19
```

And the GUI turns white (WSOD).

If I remove the galleryplus folder manually with `rm -R /var/www/owncloud/apps/galleryplus` it starts working again. 

Is this a know error, or am I doing something wrong here?

cc @oparoz

**Comment by oparoz** [comment]
You're doing it wrong ;)

You have to pick between

#### Gallery

`https://github.com/owncloud/gallery` -> `gallery` folder

 and

#### Gallery+

`https://github.com/interfasys/galleryplus` -> `galleryplus` folder

**Comment by enoch85** [comment]
@oparoz Thanks! It isn't easy when you don't know were to look. ;) I thought you merged GalleryPlus into Gallery master, and that´s why you renamed them earlier.

**Comment by oparoz** [comment]
Yes, it was merged inside the gallery repo and that's why both the namespace and folder name have changed.

It's even more confusing for people who got Gallery+ through git since their folder is named `galleryplus`, but they're now getting Gallery. But those are more advanced users who should be able to sort it out more easily.

People on Gallery+ today will run into problems when upgrading to 8.2, if they try to activate Gallery+, but a nice blog post explaining the new arrival should help clear things out.

**Comment by enoch85** [comment]
Yeah, somewhat confusing to say the least. It´s now activated in the community VM. I´ll write something about it for sure. :)

**Comment by oparoz** [comment]
Just to be sure, the community VM is always tracking the current release, correct?

**Comment by enoch85** [comment]
Yes. But right now the script is downloading from the master (https://github.com/owncloud/vm/commit/bbdac40cb0ecfb0fb2a39fd73032b91aa7a7aeb6) as I don´t see any other way to don´t have to change the script on every release. Maybe you have any better idea?

**Comment by enoch85** [comment]
@oparoz Please check if this is a correct assumption of how it will work: https://www.en0ch.se/gallery-on-owncloud-8-2/ 

Pass: oparoz

**Comment by oparoz** [comment]
I think it's the right approach. You'll have to track changes in app repos anyway to make sure you don't miss the switch to a new branch, in case there are some non backward compatible changes.

Regarding the post, you won't need to delete the app. Here is how it should work.

1) Disable Gallery+
2) Upgrade to 8.2
3) Choose to upgrade Gallery+ OR to enable Gallery

There is one major issue which I've been notified of via email: Share URLs. If you switch between apps, then you lose the links... The fix is simple via a simple htaccess directive, but it's not something everybody will be comfortable with.

**Comment by oparoz** [comment]
What I've described works for people using the app store. For people using git, they simply have to change the origin from owncloud to interfasys and then switch to the branch which matches their ownCloud version.

**Comment by enoch85** [comment]
@oparoz 

> You'll have to track changes in app repos anyway to make sure you don't miss the switch to a new branch, in case there are some non backward compatible changes.

So in other words, it shouldn´t be a problem using the master as long as the server version always is the latest?

**Comment by oparoz** [comment]
Yes, I'll try to make sure that master in Gallery+ is always for the current version of ownCloud. If it isn't it simply won't install. Not a problem for users in general, but a problem for automated tools like the VM builder.

**Comment by enoch85** [comment]
@oparoz Thank you, that would be really nice of you! :)
