### ISSUE TITLE
Pick your slideshow button disposition!

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#351]
For 9.0, we should have more actions available in the slideshow, but we have to decide which ones should always be seen and which ones should be hidden away behind 3 dots. 

In order to have constructive arguments, it would be good if each of you could browse the web and look at what popular apps are doing. They usually have large teams working on their projects. You should also reach out to your designer/usability expert friends for some input.

@jancborchardt's views are:
- The eye is drawn to the image. And even if it is drawn to the top, that’s another reason why the actions should be at the bottom. Because otherwise they will distract from the image
- The only actions which need to be visible always are Favorite, Share and maybe Download
- Download should only show there directly (instead of the more menu) for public shares, not when you are logged in to your own ownCloud where, well, you already have all the files downloaded

My views are:
- I prefer buttons at the top. I see what's available instantaneously and it works on small screens
- I agree that we should hide the less used buttons, but I'm still undecided on which ones that should be
### Shown buttons
- Favourite
- Share, **including social media sharing**
- Download
### Hidden buttons
- Delete
- Rename
- Play (slideshow)
### Unknown location
- Rotate
- Brightness
- Flip
- Colourise
### Rough proposal

![](https://cloud.githubusercontent.com/assets/925062/9883864/ef6735a4-5bdc-11e5-99f0-683851ec5e0a.png)
## The competition
- Some interfaces don't offer many options in the slideshow itself, the app has another view to manage the files themselves
- Some UI have legibility issues, but it's still interesting to see what they think is an important button
### Pyd.io

![](https://cloud.githubusercontent.com/assets/4511254/9886956/61788ee4-5bed-11e5-851b-67e6052e994d.png)
### Photoswipe

![](https://cloud.githubusercontent.com/assets/323220/9887976/bc97be44-5bf2-11e5-87a1-6932d95fee43.png)
### Trovebox

![](https://raw.githubusercontent.com/photo/frontend/master/files/creative/screenshots/web/lightbox.jpg)
### 500px

![500px](https://cloud.githubusercontent.com/assets/323220/9902932/841036c0-5c72-11e5-9793-2ea927fac239.png)
### Flickr

![flickr](https://cloud.githubusercontent.com/assets/323220/9902938/90937164-5c72-11e5-9e47-9b36bcca31c0.png)
### MS Photos

![photos](https://cloud.githubusercontent.com/assets/323220/9902944/978f8624-5c72-11e5-986b-56fe2f9a7a7e.png)
### Picasa

![picasa](https://cloud.githubusercontent.com/assets/323220/9903041/3529615c-5c73-11e5-855b-fbd188f559e5.png)

_Note: This discussion will not be for the faint of heart. You'll hear passionate arguments from all sides. There will be studies, screenshots thrown at each other. You have been warned!_
##

**Comment by jancborchardt** [comment]
Everywhere actions are at the bottom except MS Photos. Case closed on the position at least? Keep in mind the position of the Download button is a topic for 8.2, not 9.0!

**Comment by oparoz** [comment]
You're forgetting Photoswipe and in most examples there is no filename or caption at the bottom. They sometimes show the author name and it's not centred.

I've picked these examples to look at which buttons they think are important.

**Comment by jancborchardt** [comment]
We don’t have author name, and don’t really need it at the moment. Please, focus on what we have and need for 8.2 – and that is only the filename and download function. And that shouldn’t be thrown all over the place, but close together because it both belongs to the file. Thanks.

**Comment by jancborchardt** [comment]
And btw, awesome on the research! :) I don’t mean to sound like I’m shooting down discussion – but honestly here it’s just about moving the download action, and we need to fix it for the coming 8.2 release.

**Comment by oparoz** [comment]
Keep in mind that this is a discussion for 9.0 and about show/hide buttons, so that we can keep the 8.2 stuff in other "issues".

**Comment by deMattin** [comment]
Going on discussion for future versions:

Comparing with other apps has to be done carefully to not compare different intentions of use.

Is it a maintained gallery or photo show, where users have uploaded their revised pictures to be shown or is it a picture crawler, showing all images of your data space (like owncloud gallery)?

In actual environments/cams/smartphones autorotation mostly works perfect and you often don't get wrong orientated pictures. But there are also (other and older) pictures in your or others data spaces!

As I mentioned in another thread (https://github.com/owncloud/gallery/issues/349#issuecomment-140657302 and following), I see the rotation button as a really needed button in view, because you get there _all_ pictures, you have in your cloud or shared by others and they are often not maintained or rotated, if autorotation doesn't work for whatever reason.

BTW: For _my_ owncloud pictures, I need no rotation button, because my pictures (incl. old ones) are all well orientated.
But if you get shared pictures from somebody, who doesn't care of orientation, you are lost, if many of the pictures have wrong orientation.

As an example:
My mother uploaded her holiday pics and with her older digicam all portrait photos are shown in landscape. It is horribly to have a look at the pictures, if a rotation button is not quickly accessable.
(until now with oc 8.x, you have to twist your neck to view such pictures -> awful ...)

**So for me the rotation button is the most important button to be shown in a picture crawler like gallery (and prev and next picture buttons of course).**
It's abolutely more important to get a quick access button for rotation than download or share buttons in a VIEWER app for probably unmaintained pictures!
These other actions can go in a "..." menu without problems or slow down of normal useage.

If someone is another opinion, one may have had luck, not to have (often) got photos with wrong orientation ... ;)

Edit:
btw: A double action button (rotate left or right) would be best, not to click 3 times, if you have to rotate 90° sometimes left and sometimes right.

**Comment by enoch85** [comment]
I defiantly think Photoswipe is the cleanest solution here, but not totally. I haven't tested @jancborchardt design, but I like the screenshot there as well. So in other words - a combination of @jancborchardt proposal together with Photoswipe would have my :+1: .

Another thing I miss: a delete button. Imagine you go through the pictures from last nights party or whatever, some of them will be messy and blurry, and you want to delete them.

**Action today** 
- Go to the local file and delete it from either your OS (if you have the sync client installed), or the files app.

**Proposal**
- Add a delete button (same style as in the Files app) and delete it directly. Of course the same yellow field in the top should be present, just as it is in the files app if you accidentally remove something.

**Comment by oparoz** [comment]
@enoch85 - I was like you, thinking that both are clean and that it wouldn't matter if it was top or bottom, but I've changed my mind once I tried on mobile. Anyway, top/down discussion should be tracked here: https://github.com/owncloud/gallery/issues/349

Not sure I would need the delete button in the slideshow, but I have a feeling this is going to be a long discussion. The needs on the Files side are different than on the Gallery side. One for the 3-dots button

**Comment by jancborchardt** [comment]
(For what it’s worth, I think 500px has by far the cleanest and nicest design.)

**Comment by oparoz** [comment]
It's not bad, but they have very few icons. We need more screenshots from online photo apps. Maybe Google Photos, iCloud?

**Comment by LukasReschke** [comment]
![2015-09-16_16-25-37](https://cloud.githubusercontent.com/assets/878997/9907470/9c081dc0-5c8f-11e5-9ff7-a7a27ab03dca.png)
![2015-09-16_16-28-16](https://cloud.githubusercontent.com/assets/878997/9907549/fbc3c49e-5c8f-11e5-959c-cfa1bc76bb20.png)

**Comment by deMattin** [comment]
First approach might be to decide, if you want a toolbar or an overlay design.
Also 500px has a toolbar, but you don't see it, because the picture is black at the bottom.
In actual 500px it looks like that in their gallery view if you dismissed the upcomming shortcuts help (btw a nice idea!):
![image](https://cloud.githubusercontent.com/assets/5565503/9907475/9c71f84e-5c8f-11e5-84c3-812dc5f7c14c.png)
And like that, with expanded "..." menu:
![image](https://cloud.githubusercontent.com/assets/5565503/9907529/da0fe652-5c8f-11e5-94d5-7c28ff746593.png)

**Comment by jancborchardt** [comment]
Google Photos is probably nearest to where I want to go for. I mean, we can also put everything at the top. The main point is that things should not be all over the place. Either top or bottom.

And since at the top there are already things like browser controls and tabs etc it seems more grounded to put the controls at the bottom.

**Comment by deMattin** [comment]
And again as I see noone comments on it:
It isn't a good idea to compare owncloud gallery with online photo apps or social media apps.
Owncloud is none of them though it has some features of these use cases!
In my opinion Owncloud gallery has more to be compared with offline apps on PC, tablet or phone because mainly it's OWNcloud and no social media app with other targets (voting, liking, sharing on many platforms, commenting, ...)!

**Comment by jancborchardt** [comment]
@deMattin well, we have federated sharing, so the social aspect will come sooner or later. And of course we should compare to modern web apps as well.

**Comment by deMattin** [comment]
Surely compare, but with the RIGHT apps.
And I hope owncloud will never become a second facebook, flickr or whatever.
Sharing data to selected users is another thing than sharing something to public under the social media aspect (thogh sharing to public is and should be possible but without voting, liking and that social media stuff, many of the above apps are targeting)

If we are talking only about the general look and technic, it's another thing where it can and should be compared to actual and well used design by popular web apps.

**Comment by enoch85** [comment]
Ok, changed my mind. Google has exactly everyting that I would like in the Gallery app - even the delete button. It´s just perfect! And, on the top as @oparoz talked about.

**Comment by oparoz** [comment]
Thanks for all the new screenshots!

> shortcuts help (btw a nice idea!)

I did think it was a nice touch :)

> The main point is that things should not be all over the place. Either top or bottom.

For icons, yes, but I think we'll have to split filename and icons because of the limited space available in portrait

And regarding sharing, I think sharing to social media is expected, but no need to go over the top. It's just nice to be able to share the pic you're viewing.

**Comment by jancborchardt** [comment]
> For icons, yes, but I think we'll have to split filename and icons because of the limited space available in portrait

Not necessarily. Look at Android and iOS: Both actions and title in the header for most apps. We can ellipsize, and as said put excess actions in a more-menu.

**Comment by oparoz** [comment]
I'll wait for the mock ups, but in my tests it doesn't work. The Play button gets in the way.

**Comment by enoch85** [comment]
Any update here?

**Comment by oparoz** [comment]
There aren't any new buttons, so we'll re-evaluate once we need to introduce the 3 dots.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#81
