### ISSUE TITLE
Share button doesn't work any more

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#359]
The whole code we were using to show the share dialogue has been removed from `core`:
https://github.com/owncloud/core/commit/41f16e821a086d9529cc4eb3f26e24bbb1e04c72

When trying to replace it by using the new `OC.Share.showDropDown()`, I get this:

> TypeError: this.fileInfoModel is undefined

so something is telling me it's only ready for Files and it's going to be way more complicated than that to get it to work in Gallery.

So I think we're going to have to remove the share dialogue from Gallery.

cc @PVince81 @jancborchardt @karlitschek 

_Note: the share dialogue in Pictures has been a hack from the start_

**Comment by PVince81** [comment]
Either this or revert the changes in "share.js" in core to make sure that gallery, calendar and contacts are still able to use the old dialog.

But in a discussion with @DeepDiver1975 @rullzer @schiesbn it was decided that we should move the old code to each app instead of keeping it in core.

I'll have a try doing that with the calendar app as not everything from that file needs to be moved, and it might also need some namespacing.

**Comment by PVince81** [comment]
On another note it might be possible to instantiate the ShareDialogView and append it into a dropdown to make it work with the new code.

**Comment by PVince81** [comment]
The ShareDialogView should be usable for the gallery app as it's about sharing files.
In the case of calendar/contacts it might not be compatible, so that would be a situation where the old code should be moved as is.

@blizzz said he originally intended to make showDropDown work with the new dialog.
@blizzz can you have a look ?

**Comment by jancborchardt** [comment]
Well, please make sure sharing still works in Gallery, Calendar and Contacts (etc) for 8.2 – either with dropdown or via sidebar.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/19214 to make showDropDown work again for files

**Comment by oparoz** [comment]
Thanks @PVince81. I do think it would be nice to be able to use the new ShareDialogView as it would be less hackish and a first step towards using the right-sidebar :)

**Comment by oparoz** [comment]
Fixed via #367
