### ISSUE TITLE
Please, ship (and use) unminified JavaScript files

### ISSUE THREAD

**Issue by DavidPrevot** [owncloud/gallery#419]
Hi,

The `js/vendor/bigshot/bigshot-compressed.js`, `js/vendor/image-scale/image-scale.min.js`, and `js/vendor/commonmark/dist/commonmark.min.js` files are without source, that makes it close to impossible to audit security issues, as well as nearly impossible to check that no malicious code has inadvertently made its way into them.

**Comment by oparoz** [comment]
Thanks for expressing your concerns :).
Including the source won't always prevent malicious code from making it into the minified version used in the app since you probably won't be able to exactly re-create the minified version unless you know exactly which compiler has been used, with which settings, etc.
Having said that, there are issues with the way scripts are distributed.

Here is my proposal:
- Include the license and readme (if it exists) for all libraries. I thought I did, just like in the 3rdparty folder in `core`, but they're all missing :S 
- Include the non-minified version of all libraries. Making it easier to identify which version is used. Unlike composer, bower doesn't provide a lock file yet.
