### ISSUE TITLE
Questionable "nativesvg" parameter in "/api/preview/{fileId}/{width}/{height}"

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/gallery#447]
The `nativesvg` parameter is a little bit questionable. Can you elaborate what the reason here is? It does not offer any security advantage as an attacker could just set the value himself.

That said, as far I can tell this does not impose an imminent security risk as CORS routes require HTTP Basic Authentication and the file is served with a download content disposition. Personally I'd always serve the files as text file but that's only me.

That said, can we remove this parameter and default to either SVG or TXT? :smile: 

Ref https://github.com/owncloud/gallery/wiki/RESTful-API#apipreviewfileidwidthheight
##

**Comment by oparoz** [comment]
> Can you elaborate what the reason here is?

The SVG is "disarmed" by default so that it's not a problem if it's being processed by Javascript and the switch allows the consumer to get the proper media type if it needs it. I remember having issues in the past with the `core` preview API sending SVG as plain text and having browsers complaining a lot about the media type mismatch, so the same could happen to any 3rd party app using the API.

> It does not offer any security advantage as an attacker could just set the value himself

I don't understand this scenario. Who is the attacker? The app consuming the API? But then any app can be evil.

**Comment by LukasReschke** [comment]
Sure. Let me elaborate a little bit on the SVG dilemma a little bit more. I'm a little bit verbose just so that everybody who stumbles it upon in the future and never heard of it can make something out of it :)

SVG is a XML based file format that describe a vector image. To allow some more advanced features it has been decided that SVG should be able to embed JavaScript as well in it's images.

So a file with the following content would result in a browser executing the Javascript:

``` svg
<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>
```

If an attacker can define the Javascript snippet on it's own this would basically equal a stored Cross-Site-scripting (XSS). They could add JS to extract data from the instance or do other malicious stuff such as forcing the user to change his password.

As people got aware of this problem it has been decided that Javascript should only be executed when the SVG is delivered with an attachment disposition of `inline`. Also images embedded via the `<img` tag are not executed anymore.

Obviously Gallery does set the download disposition. Which is completely fine. It also sets the content-type by default to `text/plain`. However, the latter is unnecessary from my PoV, an adversary could just force you to open the file with the SVG content disposition by opening another file. They could do this by just embedding a link on a malicious website as there is no CSRF protection employed. Thus I don't see any reason for this switch here from a security PoV.

My question here is: Is there another reason for having this switch then at all? If not then we should just default to one of the both. As you mention having problems with the text mimetype I'd probably vote for the SVG one.

One should note that if the used browser supports [Content-Security-Policy](http://caniuse.com/#feat=contentsecuritypolicy) Inline Javascript does not get executed as we instruct browsers not to execute it. However, a specific vendor located in Redmond has not yet implemented CSP in their browser properly.

**Comment by oparoz** [comment]
> an adversary could just force you to open the file with the SVG content disposition by opening another file. They could do this by just embedding a link on a malicious website as there is no CSRF protection employed. 

How would the Gallery app use that link since it only opens files via its own controllers?
If ownCloud is compromised and modifies the app's Javascript or links, then it's game over anyway.
And if it's an app using the Gallery API, then it can't connect without the user's credentials. Same hurdle if it's an embedded link.

So, attacker sends you a bad SVG, then sends you a link asking for your ownCloud credentials to show you something special and that activates the code hidden in the SVG. Is that really a case we should take into consideration?

> My question here is: Is there another reason for having this switch then at all?

The main reason is that I don't know how people are going to use the API, but since this is a preview and not a download endpoint, I think it makes sense to send a SVG with its media type, even if an XML file is not an image file.

It's also the only exception. It's TXT everywhere else (internal preview & all download endpoints).

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#99
