### ISSUE TITLE
De-emphasize file extension

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#461]
What do you think about not showing file extensions at all? They belong in a file manager maybe, but not in a nice thumbnail gallery viewer like this.

A compromise would be to not show them in the overview, but only in the detail view. But ideally I’d say let’s cut them everywhere in the Gallery.

@oparoz @owncloud/designers

**Comment by oparoz** [comment]
I don't really care (for the photowall), but I think this will end up being a half-baked solution, because the rest will probably look like a file name anyway. `toast_with_PM_after_election` or `DCIMG20151102` don't look any better without the extension.
Once we have meta data, it won't be a problem anyway since we'll be able to show the image's title instead of the filename.

Also, I if we ever introduce file management feature, then it would have to make a comeback as it can happen that you have a PSD doc and it's PNG preview in the same folder and you would want to know which is which before deleting one of them, if you need to.

**Comment by carlaschroder** [comment]
What oparoz said. File extensions are essential information for file management and knowing what you're doing.

**Comment by jancborchardt** [comment]
Yeah, I was also thinking that the file name will look stupid anyway. Also good other points. Disregard this then. ;)
