### ISSUE TITLE
When in File view, when I switch from list to grid view, folders disappear

### ISSUE THREAD

**Issue by elpraga** [owncloud/gallery#462]
When I am viewing a list of folders in list view and swith to grid view, only the folders with only photos in them will stay visible, other folders disappear. 

User is not consciously choosing the Gallery app, in his/her mind he is only swithing the view on existing files. Current behaviour makes it seem that foldders suddenly go missing.

Expected behaviour:
All folders should be visible as before with large thumbnails for photos and equally large icons for files without thumbnails.

**Comment by oparoz** [comment]
As indicated [in the wiki](https://github.com/owncloud/gallery/wiki), the goal of Gallery is not to provide a grid view for files, instead, the Files app should provide that view (shouldn't be difficult since it only requires some CSS/JS changes), as requested [here](https://github.com/owncloud/core/issues/17357).

**Comment by elpraga** [comment]
That would be perfectly fine, the problem is that it switches to Gallery app without warning. Thank You for pointing out the correct place to report the issue, I was not too sure where to report it, and I misplaced it.

**Comment by oparoz** [comment]
I think it's because the switching icon is confusing, it looks like the typical grid view in a file manager, but then you land in a gallery. @jancborchardt did try to use the Gallery app icon instead, but that didn't work. I'm open to ideas on how to improve the situation.

**Comment by jancborchardt** [comment]
Well, I mean honestly the only way to clear up this confusion and do it right is to actually implement a grid view in the Files app – as you already mentioned in the past @oparoz 

This isn’t on any roadmap so far since it would necessitate maintaining a completely separate view, so it’s quite a lot of work, not only in the short term.

cc @DeepDiver1975 @PVince81

**Comment by jancborchardt** [comment]
Which is the already mentioned issue in core https://github.com/owncloud/core/issues/17357 of course. :)

**Comment by elpraga** [comment]
In that case, wouldn't it make more sense to remove the confusing switch and let peple just use the Gallery app if that is what they are doing anyway?

Or at least rename it somehow like "Open folder in Gallery app" because not leaving the current folder is the only reason to have it there..

I am just suggesting that because I got really scared that my files got missing / erased before I cought grisp of what was happening..

**Comment by oparoz** [comment]
> This isn’t on any roadmap so far since it would necessitate maintaining a completely separate view, so it’s quite a lot of work, not only in the short term.

I don't think it is, unless there is a lot of HTML embedded in the JS. You simply draw boxes instead of rows.
If it is, then it means the Filelist code needs to be refreshed to fight against bit rot.

@elpraga - The renaming would be in a tooltip. I'm not sure it would be that useful, but it's not difficult to implement if others think it's a good solution.

**Comment by elpraga** [comment]
You are probably right, much better would be to have a grid view that is a grid view and not a picture viewing app. I was just how to let people know that only pictures and folders with pictures will be visible in the grid view.

**Comment by jancborchardt** [comment]
Let’s continue in owncloud/core#17357 of which this is basically a duplicate. ;)
