### ISSUE TITLE
Performance issue for Thumbnail generation in Owncloud Pictures

### ISSUE THREAD

**Issue by svergeylen** [owncloud/gallery#57]
When displaying the content of a photo album, the computing of the gallery takes more than 15 minutes to render about 100 photos.... (This is because I run Owncloud on a raspberry PI...) and when reloading the page, it start again because the thumbnails seems to be re-create again and again...

It should be awesome to execute the thumbnail creation in background, and not when loading the page...

Should it be possible to create all the thumbnails of all photos within a CRON job ?

The best way should be to render the thumbnails after the update of a photo file (maybe through a trigger after each file update ?)

**Comment by rapITler** [comment]
Hi,

I also would appreciate if it would be possible to run a background task for newly added pics where the thumbnails automatically will be created.

In my environment (banana pi with mysql, nginx, apc, oc 7.0.4) the thumbnail creation have a huge impact to my CPU which slows down the whole system when accessing a new folder with a handful pictures.

%Cpu(s): 94.0 us,  5.4 sy,  0.3 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
 PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND
18756 www-data  20   0  360m  78m  11m R  37.3  8.9   2:38.87 php5-fpm
22963 www-data  20   0  360m  75m 9412 R  37.3  8.6   0:01.07 php5-fpm
22956 www-data  20   0  360m  75m 9412 R  33.2  8.6   0:01.48 php5-fpm
18779 www-data  20   0  360m  78m  11m R  24.9  8.9   2:39.26 php5-fpm

When the thumbnail-process runs smoothly at night I am sure it wouldn't have such an impact to my CPU.

I am new on OC and not familiar with it but I am little bit frustrated and surprised that the part around thumbnail doesn't work as expected on my (admittedly) small hardware because my goal is to move from dropbox (with thousands of pics) to my private OC where the preview of my pics are working fine. Compared to dropbox it also isn't possible to preview a pic in the android app when I am searching for one special pic (I already read about it that it will may be implemented in OC8).

@libasys: Your "five cent" is for me the way in the right direction espacially points 2 and 3 - How do you exactly do that?

May some of you have some tuning tips how I can accelerate the creation of my thumbs.
(I've already downsized the previews and the scale rate).

Thank you!

**Comment by utack** [comment]
The issue hit me again, now that the Android client also shows thumbnails.
Maybe the gallery app can get a small config option to automatically pre-generate all thumbnails with a low task priority,

**Comment by LukasReschke** [comment]
> The issue hit me again, now that the Android client also shows thumbnails.

That's completely unrelated to the gallery app. The thumbnails are generated from core.

**Comment by utack** [comment]
Interesting, thanks for telling me!
In this case maybe core could get such an option.

**Comment by LukasReschke** [comment]
Please complain at https://github.com/owncloud/core/issues/11685 ;-)

**Comment by skippyskip** [comment]
The absolutely need to fix this issue!

I have a directory witrh 390 pictures inside and the thumbnails-directory has already 784 thumbails!
They are re re re and re-created. Like this, this cloud is absolutely not usable!

FIXTHIS FOR 8.0.4 PLEASE!!!

**Comment by oparoz** [comment]
This should be fixed in 8.2, so still a few months to wait.

**Comment by skippyskip** [comment]
A few months? Wow, this is a long time ...
Remember, there are,.. I don't know how many ownCloud-Users just waiting for this.
Would be cool to have this very fast. Because ownCloud with pictures is not possible like this.

**Comment by oparoz** [comment]
Well, you have 2 solutions if you're in a hurry.

1. Use @libasys's fork of Pictures. It comes with lots of goodies, but may not be publicly available yet for oC8.
2. Sponsor the development of the feature in Gallery: https://github.com/owncloud/galleryplus/issues/22

**Comment by skippyskip** [comment]
I am not in hurry =)
There are juste several other cloud software programs. They get bigger, better and faster at the same time =/ I really want to use ownCLoud because of the perfect webinterface. But with a thumbnail-issue like this it's not cool :(

I will look your link... give me 20 minutes. and sorry for my english.

**Comment by blackm** [comment]
And there is a third option...code yourself...it's open source. :-)

If it's just a few month to wait it's great! The issue is open for a long time.

**Comment by skippyskip** [comment]
No I don't want to code myself.
Because of if I install an Update, it will be very annoying and difficult for me to re-implement my old code... I'll wait to this patch I think.

Just for the admins again: The biggtest problem is the re re and re-creation of the thumbnails.

**Comment by skippyskip** [comment]
I don't knbow exactly but there is also a huge memory leak in ownCloud.
After 2 hours of ownCloud running without up- and downloads to the cloud the free memory is belos 20 MB.

**Comment by jospoortvliet** [comment]
@skippyskip ha, you're right, if you code it yourself but have to apply it again on every update, that is very annoying.

Luckily, there is a solution for that: code it yourself and send it to @oparoz in the galleryplus app and he will maintain it for you ;-)

I'm sure he'd be happy with a solution for this.

cron.php is doing lots of background cleanup stuff, have a look. indeed, thumbnail creation could be added.

**Comment by skippyskip** [comment]
It's not good to add thumbnail creating right now to the cron because it's too buggy.

**Comment by borconi** [comment]
I might be barking at the wrong tree here, but, is there any way that the gallery still display images if I disable image preview in the config file? I'm using owncloud to handle a huge collection of photos (more than 800.000) and some of the folders (albums) contains over 100.000 images so I HAD to disable the previews in the config.php which is good and I'm happy with this, but as soon as I disable the images are not even showed when you open them (by clicking on them on them in the File app). 
Is there any way to disable only the thumbnail creation, but still be able to view the image when you open it?

**Comment by oparoz** [comment]
It's theoretically possible, but that would have to be created specifically for you and made available via a config switch.

**Comment by borconi** [comment]
Hi Oparoz.

Thank you for the quick answer (I was afraid of something like this). I don't care about the slideshow (automatic one). I'm thinking I might write myself a small app which just display the full image with php passtrough (and use client side CSS to display it correctly). I know this is WRONG for bandwidth usage, BUT for my set up where it is not  too frequently used feature it is a better option then using any CPU or memory for resizing. 

Thanks again for saving me the time of going trough all the code.

**Comment by oparoz** [comment]
That shouldn't be too difficult to create what you want
- Controller which sends back the image
- [File action in Javascript](https://github.com/owncloud/galleryplus/blob/master/js/galleryfileaction.js) which shows a div with the img tag containing the URL to the controller

Using ocdev to create the app will speed up the development process.

**Comment by oparoz** [comment]
I think we can close this. Once `core` has implemented thumbnail generation queuing, we could maybe show a message to the user if it's not ready yet, but in Gallery, the initial loading time of each album where there are no thumbnails yet should be bearable, except for the ones containing very large images.
