### ISSUE TITLE
Adding further image formats ...

### ISSUE THREAD

**Issue by w-markus** [owncloud/gallery#596]
## Feature request

**User type**: Logged-in

**User level**: Beginners
### Description

Hi all,

I just registered here, to find out how I could contribute. Though I am not sure whether the Gallery issue tracker is the right place. My interest or better what I envision is to use owncloud as a tool for the management of our lab data: we run several experiments on the same sample and finally want to share the data between the users being part of the project. It is also necessary to keep track of the project. The Task app might be useful for this ..
Anyway, most of our data is image data (2D and 3D), but graphs (1D images if you like) could be possible to.

My question to the Gallery developers is, how to add new image formats provided that I know how to convert them to some (Gallery known) preview format? Of course, I could save the data as an already available data type but then I might loose extra information that is embedded into the original file (e.g. experimental parameters). In addition, the original data might be examined by a software that expects the original data format. Therefore converting the primary data to some tagged format will not work. Storing variations of the same data makes no sense in my view, so the original data should be saved, only.

Thank you very much for the cool tool OwnCloud!

Markus

**Are you a developer willing to implement this feature?**: yes and no
My skills are definitely limited, since I am scientist not a software developer. Last php/mysql programming is more than ten years ago. I have some knowledge in python and C.

**Comment by oparoz** [comment]
> how to add new image formats provided that I know how to convert them to some (Gallery known) preview format?

You need to write a new preview format converter. That way, the original file contains all your meta data which can be made available to external apps which download the file, while Gallery can show the converted result, which can be more than the image itself if your converter "prints" the meta data on a PNG per example.

Now, regarding that converter, you can try to write it yourself, but you'll need to know how to write an ownCloud app first, because I haven't had time to launch my for-subscribers-only preview app which you could use as a base and as far as I know, nobody has written any new previews since they've been "banned" from `core`.

I see 2 solutions:

a) You're willing to learn how to write an app and a converter and will maintain it for your lab. It's not difficult, but will require some time
b) You can find someone to sponsor the development of the converter. Your programming skills will still be useful for some knowledge transfer, in case you need to make custom modifications in the future

Let me know if I got it right and what you think should be the way forward :)

**Comment by w-markus** [comment]
Yes, you got it. :-)
A converter, is it a converter for imagemagick or an extension of owncloud/gallery?

Concerning app writing. I managed to set up a development environment, though there was an issue with the path to the php5 session folder being not in user space, but that I will report elsewhere.
What would you recommend to start with in order to get some overview about what is needed for app development?

Best wishes Markus

**Comment by oparoz** [comment]
> A converter, is it an converter for imagemagick or a extension of owncloud/gallery?

It's a converter for the Preview system of ~~Gallery~~ ownCloud. So if ImageMagick can convert your format to PNG, then you have very little work to do, apart from building the app ;).

This should give you all the information you need:
https://doc.owncloud.org/server/9.0/developer_manual/app/index.html

**Comment by oparoz** [comment]
Oops, the Preview system of ~~Gallery~~ ownCloud

**Comment by oparoz** [comment]
Are you making progress? :)

**Comment by w-markus** [comment]
Thanks for coming back to this issue. Well, I do not know yet. :-)

To start from, I have both a java class file and a python script, which is based on the respective java  class file (both not written by me).
I first looked around to find a possibility to use one of these more or less directly from PHP. So far, I did not find something which may help in this respect. This may well be related to the fact, that I could not completely understand yet, how the preview part of owncloud is organized/works. In addition things may be/are constrained by working under Opensuse Linux (13.2) without root privileges (this could be lifted, with some discussions ;-) ).

Thus, I took the txt.php previewer as a template, as it directly inherits from the provider class. That's because I did not understand yet, how other classes are used to deal with individual image formats. :-)
Furthermore, the mime-type of my file type is rather application/octet-stream than image/some-format. Thus I thought, these dm3-files deserve an own class (may be wrong).

I took the python script, as I know python but not java, and began to translate it more or less literately into PHP with the first aim to get the thumbnail generator working. Just yesterday, I arrived at a point, where the python script starts to use the numpy package, which to my knowledge has no equivalent in php.

That's the current status. :-)

Best wishes

Markus

To be more specific about the file format:
[Here](http://rsb.info.nih.gov/ij/plugins/DM3_Reader.html) is the web page for the java class file and [here](https://bitbucket.org/piraynal/pydm3reader) the info for the python variant.

**Comment by w-markus** [comment]
well, I should add, that I am aware of executing python with a shell command. But how to do this in a secure way?

**Comment by oparoz** [comment]
> I first looked around to find a possibility to use one of these more or less directly from PHP. So far, I did not find something which may help in this respect.

If you use `exec`, you can call the script directly, but as you've just mentioned, it's not the safest way to do things, especially if the server is shared or public.

> In addition things may be/are constrained by working under Opensuse Linux (13.2) without root privileges (this could be lifted, with some discussions ;-) ).

You wouldn't need root, but a relaxed PHP installation letting you use `exec` 

> Thus, I took the txt.php previewer as a template, as it directly inherits from the provider class. That's because I did not understand yet, how other classes are used to deal with individual image formats. :-)

Maybe look at image.php instead, but most non-web image formats use bitmap.php which relies on ImageMagick.
I thought you would be able to use ImageMagick to get your thumbnails since you mentioned the name of that application, but apparently you have to rely on these extracting classes.
So, writing the ownCloud provider is your smallest task, the big one is to convert the image format.

### Create an ImageMagick filter
- Write an ImageMagick script which calls your Python or Java class. Sort of how RAW conversion works (and many others)
- Extend the Bitmap Preview class in ownCloud to convert your images (easy)

### Only show the extracted thumbnail

If you can execute the python script and access the generated thumbnail, you could place it in ownCloud's cache. That involves knowing how the preview system of ownCloud works internally.

### Merge the extracted thumbnails and some meta data

Same as above, but find a way to convert generated arrays into graphic elements layer on top of the thumbnail
That would require being able to dump those numpy arrays to file and then some knowledge of the GD library to process the data.

**Comment by w-markus** [comment]
> I thought you would be able to use ImageMagick to get your thumbnails since you mentioned the name of that application, but apparently you have to rely on these extracting classes.

This was probably as misunderstanding. I mentioned Imagick because I've seen that this is used in owncloud.

Why it's more secure to write an ImageMagick script to call some external code?

**Comment by oparoz** [comment]
> Why it's more secure to write an ImageMagick script to call some external code?

Actually ImageMagick has its own problems in terms of security, exactly because it executes scripts. If you don't properly validate the input, you may execute an attack against your server.
But there are ways around that by isolating it.

It's still safer than giving PHP a global `exec` permission.

**Comment by w-markus** [comment]
I think I am quite close now. So far, I exec the python script (Security will be added if the intended functionality is there) :-)

the php call is (in `core/lib/private/preview/dm3.php`):

```
class DM3 extends Provider {

    . . . .

    private function getResizedPreview($tmpPath, $maxX, $maxY) {

        $result = shell_exec('/usr/bin/python /..path to ../_dm3_lib.py ' . $tmpPath);

    . . . .

    }
}
```

In my python script `_dm3_lib.py` at the end I do:

```
if __name__ == '__main__':
    dm3f = DM3(sys.argv[1]) 
    ima = binascii.b2a_qp(dm3f.imagedata.flatten(), quotetabs=0, istext=0, header=0)
    # I also tried 
    # ima = binascii.b2a_base64(dm3f.imagedata.flatten())
    print (json.dumps([ima, dm3f.data_type_str, dm3f.width, dm3f.height, dm3f.depth]))
```

where `dm3f.imagedata` is a numpy array of 32bit signed integers.
Back in php:

```
$result_array = json_decode($result);
```

However, I can read the image dimensions etc., i.e. `$result_array[1]` to `$result_array[4]`, but so far I could not manage to get the image data in `$result_array[0]` transferred to the php world.
Any help would make my weekend. ;-)

Best Markus

**Comment by oparoz** [comment]
I suggest you look at preview.php's friend: image.php. You should be able to just "load" the content of $result_array[0] as it tries various ways to load what it's sent.

Or you could dump the image to /tmp in the Python class and load it from the PHP side.

Also, creating the DM3 class that way is not really recommended as it's an unsupported way to do it, but as long as you save the patch, it should work for the rest of the year.

**Comment by w-markus** [comment]
I "solved" the issue by generating a temporary png file by the python script, which is eventually loaded on the php side. Unfortunately, there was no imagick delegate, that could handle the data I sent back via the array entry  `$result_array[0]`.

This is the code:

```
namespace OC\Preview;

/**
 * Creates a PNG preview using a custom python script
 * to handle Gatan's dm3 files
 * @author Markus Wollgarten <wollgarten@helmholtz-berlin.de>
 * please see further credits in dm3_lib.py
 *
 * @package OC\Preview
 */
class DM3 extends Image {

    /**
     * {@inheritDoc}
     */
    public function getMimeType() {
        return '/application\/octet-stream/';
    }

    /**
     * {@inheritDoc}
     */
    public function getThumbnail($path, $maxX, $maxY, $scalingup, $fileview) {

        //get fileinfo
        $fileInfo = $fileview->getFileInfo($path);
        if (!$fileInfo) {
            return false;
        }

        $maxSizeForImages = \OC::$server->getConfig()->getSystemValue('preview_max_filesize_image', 50);
        $size = $fileInfo->getSize();

        if ($maxSizeForImages !== -1 && $size > ($maxSizeForImages * 1024 * 1024)) {
            return false;
        }

        $fileName = $fileview->toTmpFile($path);

        // setup temporary file locations
        $paths = array($fileName, tempnam(sys_get_temp_dir(), 'dm3'));

        // read the dm3 file using a python script and 
        // save a png version of it as a temporary file
        // return the path to the file and 
        // some other info regarding the dm3 file
        $result = shell_exec('/usr/bin/python lib/private/preview/dm3_lib.py ' . escapeshellarg(json_encode($paths)));

        $result_array = json_decode($result, true);

        // just for debugging, may me used to feed some database entries ?
        //foreach ($result_array as $key => $value){
        //  $m = $key.' '.$value;
        //  \OCP\Util::writeLog('core', 'DM3 says: ' . $m, \OCP\Util::ERROR);
        //}

        $image = new \OC_Image();

        $image->loadFromFile($paths[1]);

        // get rid of temporary files
        foreach($paths as $f){
            unlink($f);
        }

        $image->fixOrientation();
        if ($image->valid()) {
            $image->scaleDownToFit($maxX, $maxY);

            return $image;
        }
        return false;
    }
}
```

I used image.php as a template and overloaded the getThumbnail function.

In your last post you wrote that creating the DM3 (php?) class is not done in the proper way. This point I do not understand. What is the right way to do it?

**Comment by oparoz** [comment]
> Unfortunately, there was no imagick delegate, that could handle the data I sent back via the array entry $result_array[0]

Yep, I couldn't find one either. My suggestion was to write one as a wrapper for the python script which would print additional information on top of the thumbnail.

Are the thumbnails you're getting large enough for full screen previews?

> In your last post you wrote that creating the DM3 (php?) class is not done in the proper way. This point I do not understand. What is the right way to do it?

Hacking `core` that way is not the proper way because your file gets erased at every upgrade, so you'll have to remember to patch your installation after every update and hope nothing has changed.

I described the proper way in my original answer, you need to include your custom preview in an ownCloud app so that it makes it available to the previewmanager.

But congrats on getting it done :). To me it demonstrates the power of Open Source software.

**Comment by w-markus** [comment]
I will look into that app business, to get an cleaner integration.

Larger view would be nice, such that the image could be shown in the gallery itself. The python script deos only the fullsized version. Resizing is left to the owncloud scripts.

Thanks a lot for your guiding. And yes, open source is really cool as it allows to solve tasks really fast.

**Comment by oparoz** [comment]
> The python script deos only the fullsized version. Resizing is left to the owncloud scripts.

Then it's all good, you'll get the thumbnails in Gallery and the fullscreen previews

> Thanks a lot for your guiding. And yes, open source is really cool as it allows to solve tasks really fast.

You're welcome :)
