### ISSUE TITLE
Some SVGs break rendering

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#615]
#### Test 1
1. Enable `native_svg`
2. Launch Firefox
3. Upload a SVG which probably doesn't report any dimensions. There is a famous one called android.svg)
#### Test 2
1. With the same setup as above click on the SVG which breaks the rows
### Expected behaviour

- The photowall should show, as usual
- The image should show as usual in the slideshow
### Actual behaviour

- The row on which the SVG is inserted never ends 
- There is a tiny square in the slideshow
##

**Comment by kartik296** [comment]
Regarding the image not being viewed in slideshow- 
1- The bug is not in gallery app but the extension used ie. bigshot.js. 
2- The bug can not be reproduced in chromium based browsers (I could only do it in firefox) as these browsers by default provide the dimensions to the svg image if not explicitly specified.(Also this fixes the unlimited row error).

**Comment by oparoz** [comment]
Thanks for the extra debugging @kartik69, that will help.

**Comment by kartik296** [comment]
![screenshot from 2016-03-23 21 32 50](https://cloud.githubusercontent.com/assets/13837545/13991613/e34e56ba-f13e-11e5-8725-a734237c790c.png)
Also the image file reports this error in opera.

**Comment by oparoz** [comment]
Thanks. Maybe DOMpurify is leaving too much out...

**Comment by oparoz** [comment]
Fix is in #627
