### ISSUE TITLE
Folder preview only shows 1x1 and not 2x2 if only subfolders are in there.

### ISSUE THREAD

**Issue by deMattin** [owncloud/gallery#65]
I have a little issue with some folders in gallery+ not showing a correct 2x2 folder preview.
There are only subfolders in these folders which are having correct 2x2 previews. But there are no pictures in the folder itself. 
The folder preview containing only folders shows 1 picture preview and not a 2x2 preview.
This is a bit irritating because normaly this should only occur, if there is only 1 picture in the folder.

I see no errors reported - nor in browser nor in OC

Is this a issue or "by design"?

In debugging console of the browser it looks like the 2x2 is generated of 4 separate pictures but in issue case only one picture is asked for.
Could you give me advice to investigate this issue if it is one?

**Comment by oparoz** [comment]
This is by design, in order to go faster...
The app looks for 4 pictures in the folder directly below the current one, but any deeper and it will stop looking as soon as one is found.
The reason is that it could take a long time to try and find 4 pictures to populate the album, by digging through the folders.

What I could do though is to collect up to 4 pictures at the level at which I have found 1 instead of stopping at the 1st one.

**Comment by deMattin** [comment]
I think, this will be a good enhancement and would not last much longer.
This will help in most situations, because if there is one picture in a sub folder, it's very likely that there are others, too.
I understand the performance context and agree, that performance is more inportant than searching a long time in perhaps many subfolders for picture files only to get a better folder preview.

**Comment by oparoz** [comment]
Pushed the change to master: https://github.com/interfasys/galleryplus/commit/657c4c3f9e86db3163b8673f5e391e97c0c5cb7d

**Comment by deMattin** [comment]
Fast and working fix.
It works as expected.
Now more folder have a 2x2 preview and gallery+ is not noticeable slower.

Thank you! :+1:

**Comment by oparoz** [comment]
Great :)
