### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/gallery#68]
THe used memory while watching a slideshow increases rapidly (in my case 35 MB per picture) That means, that after the slideshow has shown 100 pictures the used memory is at 3,5 GB + initial memory. 

I guess there is a problem with the caching of the images. I just had a quick look at the source and it looks like that there is a cache for already downloaded images. ~~Maybe we should restrict that size and throw out old images after this limit is hit.~~ The caching should be done by the browser.

After it hits some limits the tab just crashed - "He's dead, Jimmy" in Chromium.

**Comment by oparoz** [comment]
I'm closing this as it's a lot less likely we encounter this in the next Gallery, since we're loading thumbnails and not the original image.

It's still an interesting issue, because it speeds things up if we let the browser cache images, but then we can run out of memory...

**Comment by pascalBokBok** [comment]
What is "the next Gallery?" Owncloud 8.2 or...?

The core problem is that Gallery does not allow the browser to manage it's memory because it explicitly keeps the images in memory - if you removed them after having shown them then you would be using the browsers cache, it would be written to local disk and still be in disk cache memory unless the memory was busy with something else.
Removing the images from explicit memory in between showing them is the best - because the browser and OS will always be better at managing the memory than we will.

**Comment by oparoz** [comment]
@pascalBokBok - It's the rewritten version of Pictures that you can already use today and which will be the officiall app in 8.2.

In that version, we trust jQuery and the browser to give the memory back since each picture is removed using [`.empty()`](https://api.jquery.com/empty/). In reality, I think it takes a  while for the garbage collector to kick in though.

If you see a problem with this approach or are aware of other areas where a leak could happen or memory is wasted, please open a ticket at https://github.com/owncloud/galleryplus/issues

**Comment by pascalBokBok** [comment]
ok :+1:
