### ISSUE TITLE
[enhancement request ] Reverse order

### ISSUE THREAD

**Issue by deMattin** [owncloud/gallery#90]
As I have many pictures in my account I miss a feature to revert the order of the previews.

In a folder with  many folders it shows (and generates) the oldest folders/pictures first because of A-Z order.
But often (in my case "mostly") I want to see the **newest** pictures and folder first (Z-A).

So it would be a nice feature, to have the opportunity to revert display, transfer and also generation of the previews.

A simple switching caret symbol like in the files app would be the only modification in GUI and I think reverting the complete routine from A-Z to Z-A could not be much enhancement in code because there is a sorting of this already implemented (at a central point?) as it is now already alphabetical.

Would this be as simple as I think and do you like the idea?

**Edit:**
Is this the part of "gallery.js" to be modified?

``` javascript
// fill the albums from Gallery.images
Gallery.fillAlbums = function () {
    var sortFunction = function (a, b) {
        return a.path.toLowerCase().localeCompare(b.path.toLowerCase());
    };
```

**Edit2:**
I reverted the function call and it did it - sorting order is reverted ...

``` javascript
// fill the albums from Gallery.images
Gallery.fillAlbums = function () {
    var sortFunction = function (b, a) {
        return a.path.toLowerCase().localeCompare(b.path.toLowerCase());
    };
```

**Comment by oparoz** [comment]
Reversing the order is just one of the sorting filter we should implement. See #91

**Comment by deMattin** [comment]
But this enhancement is much more work to do, if you want to add this much of sorting options and open GUI questions.
Although I would like to see it, is there a chance for a quick and simple (temporary) solution for only revert sorting with only the caret switch sign right next to the switchbutton to fileview?

**Comment by oparoz** [comment]
The problem is that it touches the UI and when that happens, I want to get confirmation of people who work on those sort of things all day long.
If you know people who can come up with designs or if you've seen this implemented in other core apps, I'm more than happy to see if it would work. I just can't spend time designing interfaces atm.

**Comment by deMattin** [comment]
I thought of the same behaviour as in fileapp to sort and change sorting for names, size and date.
But we have no "name" field in gallery+ ... :/

**Comment by oparoz** [comment]
Exactly. We don't have columns, only the breadcrumb space which gets reduced every time we go down a folder.

**Comment by deMattin** [comment]
We have the "Share" Text-Button on the right.
Left to this button a simple:
![image](https://cloud.githubusercontent.com/assets/5565503/6652335/b766d982-ca6b-11e4-8ad2-25e596f32e66.png)   switching to:   ![image](https://cloud.githubusercontent.com/assets/5565503/6652351/ddd06d90-ca6b-11e4-8eb5-bead6498acbe.png) ?
The caret / triangle is part of the core images.

I think, the frames of this are generated in all apps with a core function like here in the file app and not part of the "picture" or text:
![image](https://cloud.githubusercontent.com/assets/5565503/6652376/6a094fac-ca6c-11e4-9c7f-5b200b626f92.png)

**Comment by oparoz** [comment]
That's why I want designers to get involved. I think a button for this would be too in-your-face for the small caret and if we use a sort button, then it's another big button up there with the rest. I think there should be a new control which can be used for all sort of things or maybe a generic button revealing a slidedown containing a panel with various tick boxes for the options.

**Comment by deMattin** [comment]
You know the gallery enhancement for OC 7 from Libasys?
https://ssl.webpack.de/demo70.libasyscloud.de/owncloud/index.php/apps/gallery/ (demouser/demouser)
https://github.com/libasys/ownCloud-7.0.3/tree/master/apps/gallery

He implemented sorting and a bunch of additional features on full picture view.
I liked it very much and I see no GUI break there.
Could this be used as an inspiration for some enhancements?

**Comment by oparoz** [comment]
Yep, he's completely changed the design. I don't think it would work with a row of grey ownCloud buttons. That's why I think using an easily recognisable area with some specific buttons could be beneficial, but we need designers to come up with mock ups which can be accepted as the future direction.
There was also a discussion regarding enabling the sidebar like in Files. It could slideout to show various options such as filters, but that won't happen unless the UI guys get involved.

**Comment by deMattin** [comment]
Sidebar reduces space for pictures.
In files it doen't matter but in gallery you don't need the settings so often and space is better used for previews, I think.
Hope, that some GUI experts will have a look at this soon ...
