### ISSUE TITLE
Flat view - all images in current and sub-directories

### ISSUE THREAD

**Issue by osos** [owncloud/gallery#95]
It would be nice to able to switch to a view-mode where all images in the current directory/folder and sub-folders are shown in the grid, and the ability to scroll through the images - iOS style.

Sort by date, filename, folders etc.
##

**Comment by oparoz** [comment]
So you want to have hundreds of thumbnails on one page and to be able to sort them

There are 3 missing requirements for this to happen:
1. Stream data about a file as soon as it's collected, so that the view can be built without having to wait until we have information about the whole cloud
2. Show thumbnails as soon as they're received #29 
3.  Implement sorting filters #91

Then, if sorting by folder, we would need some sort of separation between groups of pictures.

2) and 3) will probably happen at some point, but this request seems to be the only one so far really needing 1).
It's also possible to do it without it, but it would have to be turned on via a user setting as it would slow down the app too much to be the default behaviour.

**Comment by osos** [comment]
Hmm, sounds like this is not straightforward.

But yes, basically I would like a gallery which can be optimized for smart-devices and work ala the Photo-app on iOS. This is especially great for family photos and the like.

**Comment by oparoz** [comment]
The advantage these native apps have is that they build a database within the app, on the device. So when you load the app, it uses that to quickly build the view. 
It's something we can't easily compete with as each user loads the app in a potentially different browser.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#24

**Comment by spoorun** [comment]
Copied from original issue: owncloud/gallery#697"
From @olantrust on July 23, 2016 13:33

"A timeline view to be available alongside the existing view types.
In time line view, photos are ordered by EXIF metadata (#221), if that is missing they are sorted by created date, and then modified date.
The User see photos in chronological order, most recent at the top.
There is a slider bar which the user can move slowly to move between days, more quickly to move between months, and on continued moving can move between years.
As is available in most modern photo gallery viewing applications.
